### ISSUE TITLE
xray目录扫描误报？

### ISSUE THREAD

**Issue by zglaozhu** [chaitin/xray#1025]
xray目录扫描貌似只基于返回是否200 很容易误报
是否可以添加基于返回内容/大小的判断呢

**Comment by virusdefender** [comment]
其实不是这样的，我们首先会去判断页面相似度，判断是否是一个通用页面（404之类的），然后对于每种敏感文件，我们都写了页面特征的规则。

如果你遇到了误报可以点一下报告中的 “这是误报” 的反馈，或者去除敏感信息之后贴在这里看下。

先 close 了，有问题可以随时回复。
