### ISSUE TITLE
扫不出来东西，只有dirscan和baseline

### ISSUE THREAD

**Issue by Posee1don** [chaitin/xray#1047]
比如我看有的issue中回答里提到的testphp.vulnweb.com，结果是这样子
![image](https://user-images.githubusercontent.com/45538332/105809309-6b298f00-5fe4-11eb-9c73-63a0bb4aedfc.png)
然后在扫自己的无论是xss-labs还是dvwa也都没有xss或者sqli注入漏洞，只能最多看到几个dirscan漏洞。
想问问大佬这可能是什么原因？

**Comment by phith0n** [comment]
issue不解决此类问题，建议来讨论群里提问。
