### ISSUE TITLE
cland反连平台扫描日志报group not found for event

### ISSUE THREAD

**Issue by hashwormer** [chaitin/xray#1058]
使用xray扫描过程中报"group not found for event &reverse.Event{ID:40, GroupID:"9gbh", UnitId:"fh8v", TimeStamp:1612504452159, EventSource:"internal", EventType:"http", Request:"GET /i/67ff15/9gbh/fh8v/ HTTP/1.1\r\nHost:........ ," cland反连平台也出现http日志，但是扫描报告结果没有对应的漏洞报出来。不知道为什么有GroupID还会报没有发现event。至少应该能查到当时发出的request吧

**Comment by virusdefender** [comment]
是反连平台单独部署的模式还是和 xray 在一起的模式啊

**Comment by hashwormer** [comment]
> 是反连平台单独部署的模式还是和 xray 在一起的模式啊

是反连平台单独部署的模式

**Comment by virusdefender** [comment]
感觉有几个可能

 - 这个反连请求来的比较晚（比如一些定时任务的命令注入）
 - 有多个 xray 扫描端都在使用同一个反连平台

**Comment by hashwormer** [comment]
> 感觉有几个可能
> 
>     * 这个反连请求来的比较晚（比如一些定时任务的命令注入）
> 
>     * 有多个 xray 扫描端都在使用同一个反连平台

感谢解答。感觉可能第一种情况的可能性比较大。尝试了几次和我扫描的任务比较同步，应该不存在其他人使用反连平台的可能。

**Comment by virusdefender** [comment]
可以感觉反连回来的的 ip 做一些进一步的尝试
