### ISSUE TITLE
何时可以对接钉钉啊

### ISSUE THREAD

**Issue by Oldman19** [chaitin/xray#1189]
何时可以对接钉钉啊，server酱总封号，打赏也封，企业微信没有钉钉用的多吧。

**Comment by phith0n** [comment]
网上有一些介绍如何对接钉钉的文章：<https://www.google.com.hk/search?q=xray+%E9%92%89%E9%92%89>

**Comment by Oldman19** [comment]
> 网上有一些介绍如何对接钉钉的文章：[https](https://www.google.com.hk/search?q=xray+%E9%92%89%E9%92%89) : [//www.google.com.hk/search?](https://www.google.com.hk/search?q=xray+%E9%92%89%E9%92%89) q [=](https://www.google.com.hk/search?q=xray+%E9%92%89%E9%92%89) xray+%E9%92%89%E9%92%89[](https://www.google.com.hk/search?q=xray+%E9%92%89%E9%92%89)

hh，我只想这看官方文档了，忘记谷歌了，感谢大佬
