### ISSUE TITLE
爬虫模式下，多个cookie应该如何在config.yaml配置？

### ISSUE THREAD

**Issue by WillieMatthewLiu** [chaitin/xray#1255]

**Comment by nsvicp** [comment]
DVWA 实例：Cookie: PHPSESSID=1uakhu9mmqvkjps44tcjrgl914;security=low

**Comment by Jarcis-cy** [comment]
正常写在一起就好了，如果是多个站点的，每个站点不同cookie的话，确实还不支持这样配置
