### ISSUE TITLE
http配置中的优化

### ISSUE THREAD

**Issue by ssrsec** [chaitin/xray#1265]
xray支持在配置文件中做http(s)代理。
https://docs.xray.cool/#/configration/http

使用中发现这样一个问题，如果我的代理只支持http或者只支持https，当我扫描的目标中包含http和https两种类型的url的时候，不得不分开去扫描，比较麻烦。

能不能使xray的配置文件中可以同时配置http和https的代理，然后根据url自动去调用代理。

**Comment by Jarcis-cy** [comment]
感觉比较小众，如果有比较常见的示例，可以新提issue
