### ISSUE TITLE
Proxy Failed

### ISSUE THREAD

**Issue by yunzhonghe85** [chaitin/xray#1272]
Proxy Failed [Why?]
199 "martian" "dial tcp: i/o timeout" "Tue, 25 May 2021 14:15:58 GMT"

**Comment by yunzhonghe85** [comment]
我在macos10.13.4，使用xray1.7.1的时候，在浏览器上出现的这个提示。

**Comment by virusdefender** [comment]
这个就是和你要访问的目标连接超时了，比如网络不稳定、对方有 waf 之类的。
