### ISSUE TITLE
Xray高级版BUG反馈

### ISSUE THREAD

**Issue by sinlee1** [chaitin/xray#1377]
- 版本：Windows_1.7.1

+ 通过VPS上进行扫描，目标url大概上万个，批量扫描，经过几天的测试会出现如下报错并强制结束，因是通过命令行输出的结果，所以无法看到第一行报错的原因和日志

![1](https://user-images.githubusercontent.com/29684167/127958723-f8a3799c-f892-48d0-99ed-1c21551acc9c.png)

**Comment by xxxNull** [comment]
看这样子是js虚拟机崩了

**Comment by phith0n** [comment]
看起来是的，不过需要等一个能够复现的页面样本
