### ISSUE TITLE
建议支持命令行配置include  exclude

### ISSUE THREAD

**Issue by tzxfl** [chaitin/xray#14]
在 mitm 的配置部分还有两项配置值得注意：

includes表示只扫描哪些域。比如 *.example.com 只扫描 example.com 的子域
excludes 表示不扫描哪些域。比如 t.example.com 表示不扫描 t.example.com

建议支持 --includes  xxx.com  --excludes  sss.com

**Comment by zema1** [comment]
暂时不打算给这种小的配置项添加命令行参数，因为类似的配置项太多了。
