### ISSUE TITLE
xray burp联动，出现证书错误

### ISSUE THREAD

**Issue by owl-lwo** [chaitin/xray#1409]
xray burp联动，出现证书错误
要么弹xray的证书页面
要么弹burp的证书页面
请问是要怎么设置？

**Comment by winkdoge** [comment]
我只有访问这个站http://testphp.vulnweb.com/，才会报xray500错误，别的都正常 不明白为什么？

**Comment by Jarcis-cy** [comment]
> xray burp联动，出现证书错误 要么弹xray的证书页面 要么弹burp的证书页面 请问是要怎么设置？

可能是网站在挂了代理后无法访问了,才会出现这个问题
