### ISSUE TITLE
ubuntu linux64位下报段错误

### ISSUE THREAD

**Issue by youki992** [chaitin/xray#1415]
ubuntu linux64位下报段错误，这是什么原因呢
![QQ截图20210922095037](https://user-images.githubusercontent.com/60724505/134270971-646438d0-fdf0-42d8-a58a-d04b0da0dff7.png)

**Comment by youki992** [comment]
已赋予执行权限

**Comment by youki992** [comment]
报这样的错误

**Comment by virusdefender** [comment]
需要运行 `dmesg -T` 将 xray 报错错误时间的日志发一下

**Comment by youki992** [comment]
![QQ截图20210922104322](https://user-images.githubusercontent.com/60724505/134275253-db57d38a-c612-4dca-9ae0-decbab65fea5.png)
您好我看这边没有出现今天的报错日志

**Comment by virusdefender** [comment]
`md5sum xray_linux_amd64` `file xray_linux_amd64` 和 `uname -a` 的结果贴一下看看呢

**Comment by youki992** [comment]
![QQ截图20210923092729](https://user-images.githubusercontent.com/60724505/134442596-ed65deb9-0424-4702-8172-519ad44183a6.png)

**Comment by phith0n** [comment]
我和你的不一样诶

```
$ md5sum xray_linux_amd64
2e06b17080d5a2939dbfd487e109f67c  xray_linux_amd64
```

**Comment by youki992** [comment]
> 我和你的不一样诶
> 
> ```
> $ md5sum xray_linux_amd64
> 2e06b17080d5a2939dbfd487e109f67c  xray_linux_amd64
> ```

这。。。不知道是啥原因，难不成是文件损坏了
