### ISSUE TITLE
File Multiple Scan

### ISSUE THREAD

**Issue by secfb** [chaitin/xray#1426]
Hello, I want to do multiple xray scans on a file.

```ruby
cat 1.txt
https://test1.example.org
https://test2.example.org
```
---------
```bash
cat 1.txt|cut -d / -f3

https://test1.example.org
https://test2.example.org
```

```powershell
cat 1.txt|xargs -I@ bash -c "xray webscan --basic-crawler @ --html-output $(echo "@"| cut -d/ -f3).html"
```
I want it to output as below.
test1.example.org.html
test2.example.org.html

**Comment by Jarcis-cy** [comment]
It looks like you want a target to output a report, which will be possible in xray 2.0 with the go plugin, subscribe to vulnerability events, customize report outputs
