### ISSUE TITLE
插件检测能力：zabbix-authentication-bypass.yml

### ISSUE THREAD

**Issue by ghost** [chaitin/xray#1441]
该插件判断条件存在不完整性：
![图片](https://user-images.githubusercontent.com/36068966/139008554-0b7abc3b-19b0-47f7-b828-58b4f658ece0.png)
但是不同搭建方式该标题会不一样
正常安装方式：<title>Dashboard</title>
docker启动方式：<title>Zabbix docker: Dashboard</title>

而且另外一个检测条件在实际判断时也存在检测不到问题

**Comment by mashiro01** [comment]
这个复现过后确认是有问题的，下个版本之前会完成修改
