### ISSUE TITLE
[reverse:server.go:178] server shutdown

### ISSUE THREAD

**Issue by Mr-xn** [chaitin/xray#15]
如题，大量报 `[reverse:server.go:178] server shutdown`  
或者是 `request to http://www.xxxx.com/debug.txt failed, retrying (1 / 1)...` 程序终止...  
**But**，同样的网站和网络环境，换另一个工具扫，没问题，可以扫出来一些常规敏感文件。
IP也没有被拉黑，专门找了一个没有WAF的测试。  
希望可以给出个可能的原因结果，个人猜测：  
1. 有可能是程序设置的默认线程并发太高？将来是否可以手动设置线程数量  ？  
2. 没有随机UA？
3. 线程之间设置随机延迟？将来也可以手动设置延迟？

**Comment by virusdefender** [comment]
首先你使用的 url 模式还是代理模式呢？

在扫描器退出的时候，打印 `reverse server shutdown` 是正常的，如果是中间过程中，还麻烦再多给一些日志。关于 reverse server，参考 https://chaitin.github.io/xray/#/guide/reverse

扫描器提示请求失败，这个可以尝试以下办法

 - 降低扫描器并发，在配置文件中 `max_qps ` `max_conns_per_host `
 - 提示失败的时候，使用浏览器或者 curl 去测试网站访问情况，而不是扫描器退出之后再去测试。

如果有其他的问题或者更新描述，请继续回复。

**Comment by monstersb** [comment]
感觉这个输出其实也不太表意，第一眼看到 server shutdown 都没懂啥意思。

**Comment by Mr-xn** [comment]
> 首先你使用的 url 模式还是代理模式呢？
> 
> 在扫描器退出的时候，打印 `reverse server shutdown` 是正常的，如果是中间过程中，还麻烦再多给一些日志。关于 reverse server，参考 https://chaitin.github.io/xray/#/guide/reverse
> 
> 扫描器提示请求失败，这个可以尝试以下办法
> 
> * 降低扫描器并发，在配置文件中 `max_qps ` `max_conns_per_host `
> * 提示失败的时候，使用浏览器或者 curl 去测试网站访问情况，而不是扫描器退出之后再去测试。
> 
> 如果有其他的问题或者更新描述，请继续回复。

在url模式的中间过程出现这些信息，且在扫描过程中我也可以访问网站正常浏览。  
![其他工具正常扫描](https://s2.ax1x.com/2019/07/03/ZYopOx.png)  ![url模式失败](https://s2.ax1x.com/2019/07/03/ZYoZpd.png)
同一个网站在xray的代理模式是可以正常运行。

**Comment by virusdefender** [comment]
url 模式最后 reverse shutdown 是正常的

**Comment by Mr-xn** [comment]
> url 模式最后 reverse shutdown 是正常的

好吧。。。这表达 正常结束用 task end 这样表意点吧。。。照顾一下我们这些语文不好的 :sweat_smile:
