### ISSUE TITLE
SQL注入 延迟盲注时间和配置文件中的不一致

### ISSUE THREAD

**Issue by xsser** [chaitin/xray#1537]
最近看到一个请求的payload是
`timezone":"8/**/and/**/2=DBMS_PIPE.RECEIVE_MESSAGE('f',0)"`

只延迟0秒。。？？？这是在搞笑。。

X-ray版本是version: 1.8.2/79e7dd56/COMMUNITY

配置里是
![图片](https://user-images.githubusercontent.com/1850771/143408398-be2b7ad5-6574-47a4-901b-3e93d9fc859f.png)

**Comment by virusdefender** [comment]
这两个配置没有关系，延迟 0 秒的是用于验证网络延迟的，是预期行为。

**Comment by xsser** [comment]
> 这两个配置没有关系，延迟 0 秒的是用于验证网络延迟的，是预期行为。

那这个延迟注入0秒的。。意义是…… ？？

**Comment by xsser** [comment]
> 这两个配置没有关系，延迟 0 秒的是用于验证网络延迟的，是预期行为。

我这是爆出来的漏洞payload是这个， 如果是用于验证网络延迟那应该是你扫描器自己的参数使用，和运营的人员看到的漏洞没关系吧

**Comment by Jarcis-cy** [comment]
这个的目的是为了查看让网站sleep 0秒时,网站的响应时间,从而判断真实的让其sleep的时间的准确性
