### ISSUE TITLE
xray分配内存过多被系统killed，这是bug？

### ISSUE THREAD

**Issue by pandak1d** [chaitin/xray#1543]
[-]xray ERROR: Command '['/root/tools/Watchdog/client/urlscan/xray/./xray', 'webscan', '--listen', '127.0.0.1:7778', '--webhook-output', 'http://12
7.0.0.1:5000/webhook']' died with <Signals.SIGKILL: 9>.
[INFO] 2021-11-29 11:13:28 [default:entry.go:181] Memory: Alloc = 2208Mb TotalAlloc = 566833Mb Sys = 4022Mb NumGC = 2095

**Comment by virusdefender** [comment]
- 日志应该还会打印 pending 了多少请求，这个麻烦提供一些
- 看上去 xray 占用了大概 2G 内存，系统内存是多少呢？
- 相关文档 https://docs.xray.cool/#/guide/faq?id=xray-%e5%9b%a0%e4%b8%ba-out-of-memory-%e8%80%8c%e5%b4%a9%e6%ba%83%e6%88%96%e8%a2%ab%e6%9d%80%e6%ad%bb
