### ISSUE TITLE
关于 path 问题解决的一个提案

### ISSUE THREAD

**Issue by yywing** [chaitin/xray#1555]
![图片](https://user-images.githubusercontent.com/22928185/146339711-ba58d452-4a7b-434e-8711-1ec21bf03b12.png)

**Comment by yywing** [comment]
相关的 issue：
#1477
#1460
#1097

**Comment by Jarcis-cy** [comment]
r1跟r3的那个path是不是写错了？除了换了个字母没啥改变啊，那请求的地址怎么不一样了？

**Comment by Jarcis-cy** [comment]
r1那个应该是^{{inputRoot}}/b吧

**Comment by yywing** [comment]
> r1那个应该是^{{inputRoot}}/b吧

是的 改了 - -

**Comment by likewhite** [comment]
这个方法如果可以实现，感觉可行

**Comment by yywing** [comment]
已经实现了
