### ISSUE TITLE
爬虫Rad的建议与想法

### ISSUE THREAD

**Issue by v8blink** [chaitin/xray#1557]
Rad 是一款非常优秀的爬虫，我想给 Rad 增加污点追踪（Taint tracking）功能，用于检测 XSS。
我目前已经在 V8 内核中实现了这一功能，并且使用 crhomium 90 浏览器实现了 XSS 检测，我想把这个功能和 Rad 结合起来，亦或贡献这个功能给 Rad... ...
以上是我的想法，想与 Xray 的师傅交流一下。

**Comment by chinaykc** [comment]
方便的话，加我微信私聊一下吧，chinaykc
