### ISSUE TITLE
TIMEOUT FROM FIREWALLS

### ISSUE THREAD

**Issue by elabdi** [chaitin/xray#1567]
hello guys thank you for this awesome tool
I need help to bypass the firewalls using proxies cause when the target system detects the tool it blocks it and keeps getting timeout error, how can I bypass this either using proxy list or is there any other solution.
Best Regards

**Comment by Jarcis-cy** [comment]
It is recommended to configure parameters such as ua in the headers to try to simulate a browser, but this does not solve most cases, xray is blocked because of the large number of payloads sent carrying the attack signature, so it is very difficult to bypass firewalls
