### ISSUE TITLE
Help to compile "reverse"

### ISSUE THREAD

**Issue by Teicu** [chaitin/xray#1575]
Hello, 

Can someone explain where exactly I can add my ceye or burpcollaborator account? And how should this be done?   

I don't understand if they can be added and where exactly
  
Thanks 

<img width="776" alt="Screenshot 2022-01-20 at 21 57 35" src="https://user-images.githubusercontent.com/1572822/150413422-3d10e22b-df06-4bc2-8e4e-46da7bdfe1b0.png">

**Comment by Jarcis-cy** [comment]
Xray currently does not support ceye and burpcollaborator, but xray can build a reverse connection platform by itself. It is recommended to check the tutorial https://docs.xray.cool/#/guide/skill/reverse
