### ISSUE TITLE
Xray设置SSR代理，流量不走代理

### ISSUE THREAD

**Issue by zzh1805656080** [chaitin/xray#1586]
我在Xray的配置文件中里http->proxy里面设置了SSR本地监听的HTTP代理127.0.0.1:1087。使用Xray对myip.ipip.net进行访问，发现还是我的本机IP，并不是代理ip。
系统：MacOS 12.0.1

**Comment by garyreload9527** [comment]
+1 老哥 后面解决了吗

**Comment by zzh1805656080** [comment]
> +1 老哥 后面解决了吗

并没有解决，然后一直没用Xray

**Comment by garyreload9527** [comment]
> > +1 老哥 后面解决了吗
> 
> 并没有解决，然后一直没用Xray

我去再想想办法 我设置了全局代理 它还是没有包。因为浏览器还是要监听7777

**Comment by Jarcis-cy** [comment]
可能是那个时候的版本的一些bug？上游代理方面似乎一直没咋出现过问题，如果还在用，可以试试新版本，有问题随时再提新issue，感谢反馈！
