### ISSUE TITLE
设置detect_sqli_in_cookie:为false还是在cookie中插入payload

### ISSUE THREAD

**Issue by liang960215** [chaitin/xray#1591]
![image](https://user-images.githubusercontent.com/44635826/158587224-30de79e6-e1ca-42f0-9668-b73ae5b64b62.png)

![image](https://user-images.githubusercontent.com/44635826/158587373-95d37c56-b215-45f7-a4fd-d4412be8c8f5.png)

**Comment by Jarcis-cy** [comment]
是个bug,已经修复,感谢反馈,下版本就不会了
