### ISSUE TITLE
全局变量载荷 (payload)可以按序执行吗

### ISSUE THREAD

**Issue by NHPT** [chaitin/xray#1612]
全局变量载荷 (payload)可以按序执行吗，测试发现只是选其中的一个执行一次，continue变量存在的意义是什么

**Comment by Jarcis-cy** [comment]
payload的使用示例可以参考这个：https://docs.xray.cool/#/guide/skill/payload

payload遵循最小发包量的原则，所以在命中后，就会停止发包，当使用`continue: true`后，脚本就会在一个payload命中后继续执行完后续的payload
