### ISSUE TITLE
xray proxy报错

### ISSUE THREAD

**Issue by YuanBenSir** [chaitin/xray#1619]

**Comment by YuanBenSir** [comment]
设置好了代理 安装了证书但是 一些站点会报错
![image](https://user-images.githubusercontent.com/100994165/166160802-a654c8d2-3d9c-48f2-afda-d43b9392abac.png)

**Comment by Jarcis-cy** [comment]
这证明xray无法访问到对应的地址，可以尝试在xray的上层挂一层burp看有无返回，具体是什么情况
