### ISSUE TITLE
xray_linux_arm.zip 发错包了，但是linux_arm64是对的

### ISSUE THREAD

**Issue by pythonmandev** [chaitin/xray#1630]
xray_linux_arm:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=wbdRz-bDKj-fMlQVX3_U/0aZx8B-_wg0SL6IZhqBH/cUYmQIbqCO7nfVX_g7Mz/-aOgrS8VfR6ZUg0RR_ah, stripped
xray_linux_arm64:     ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=U6EGKkmXF73lDOpHOgdp/um5Q9wuA3TNo1uAycF0k/uUdcBueaTHcUG91pkJdm/RoRngeKJOUaPzDE75L1f, stripped

希望可以提供一个树莓派4b可以跑的版本，谢谢

**Comment by Jarcis-cy** [comment]
树莓派4b的系统架构应该是ARMv8的，xray_linux_arm64编译出的也是ARMv8的，所以应该可以正常使用

同时感谢反馈xray_linux_arm的问题，这个问题将在下个版本修复，修复后，xray_linux_arm将会是一个arm32位的程序
