### ISSUE TITLE
独立部署反连平台，前端跨域报错

### ISSUE THREAD

**Issue by kkll5875** [chaitin/xray#1633]
![image](https://user-images.githubusercontent.com/52806749/176812959-1d99af98-e5f2-4ec9-a680-8d803776973f.png)
![image](https://user-images.githubusercontent.com/52806749/176813056-7d9e3367-9b4c-491e-bff5-1e059d5e63a6.png)

**Comment by gjm-anban** [comment]
+1 部署在外网会报错  chrome版本103 报错如下
cland/js/chunk-vendors.2deb4544.js' from origin 'http://x.x.x.x' has been blocked by CORS policy: Request had a target IP address space of `unknown` yet the resource is in address space `local`.

**Comment by Jarcis-cy** [comment]
确实没有复现，建议先试试新版本，如果还是存在问题，请提新的issue，并详细描述部署的版本以及机器情况
