### ISSUE TITLE
反连平台报错[WARN] 2022-07-18 00:04:31 [default:client.go:235] request to http://ip:8081/_/api/fetch failed, retrying (1 / 3)...

### ISSUE THREAD

**Issue by zhibx** [chaitin/xray#1637]
[WARN] 2022-07-18 00:04:31 [default:client.go:235] request to http://ip:8081/_/api/fetch failed, retrying (1 / 3)...
[WARN] 2022-07-18 00:04:51 [default:client.go:235] request to http://ip:8081/_/api/fetch failed, retrying (2 / 3)...
[WARN] 2022-07-18 00:05:11 [default:client.go:235] request to http://ip:8081/_/api/fetch failed, retrying (3 / 3)...

会一直持续不断的报上面这个错误

反连平台一直报错，正常使用web访问有时候正常有时候卡顿。可以更改哪里的设置解决吗？
![1658073795854](https://user-images.githubusercontent.com/82183981/179410829-8c01073c-ddb7-4675-bb1e-5cad4cd6d039.png)

**Comment by u21h2** [comment]
遇到了同样的问题

**Comment by djerryz** [comment]
同样糟糕的情况，而且一旦Retry整个代理的流量都变成502，上层逻辑都出问题了，且这部分URL不进任务队列

**Comment by u21h2** [comment]
> 同样糟糕的情况，而且一旦Retry整个代理的流量都变成502，上层逻辑都出问题了，且这部分URL不进任务队列

我这边测着反连平台服务端开在127.0.0.1是不会阻塞的 比如127.0.0.1:5001 然后需要用端口转发 VPS监听公网IP的5000端口后转发到127的5001 这样xray客户端就用公网IP的5000端口 这样可以勉强用

**Comment by houdada888** [comment]
请问有人解决的吗？，还是配置问题呢？

**Comment by Jarcis-cy** [comment]
这是一个探活的报错，一般来说就是客户端与服务端之间的通信导致的报错，所以大概率是网络问题，且反连是没有走代理的，所以服务端如果部署在墙外，可能会出现这样的问题。
在xray2.0中，我们会提供更灵活的反连的客户端，可以支持自己接其他的反连平台，尽量避免这样的情况
