### ISSUE TITLE
OOB 支持Interactsh 

### ISSUE THREAD

**Issue by djerryz** [chaitin/xray#1650]
嗨，我最近尝试集成Xray和nuclei, 对于反连检查 xray reverse 要求监听53端口，遗憾的是如果部署Interactsh client也会要求监听53端口。
这导致同时使用两款工具会需要两台设备部署OOB， 是否xray能支持配置Interactsh作为反连server端。

**Comment by Jarcis-cy** [comment]
我们后续会出类似Interactsh的在线api,可以期待一下
