### ISSUE TITLE
请问crlf 注入功能如何使用

### ISSUE THREAD

**Issue by HiJames93** [chaitin/xray#1667]
我搭建了一个有crlf注入漏洞的靶场，
![图片](https://user-images.githubusercontent.com/58398745/190573610-fb86edd3-dfce-4551-b999-c4ef3942e0b4.png)
当我用xray执行如下命令时却什么也没扫到
`xray --log-level debug ws --plugin crlf-injection -u http://10.0.0.131:8080/%0d%0aSet-Cookie:%20a=1`
![图片](https://user-images.githubusercontent.com/58398745/190570682-f77861e8-ec9a-44b9-918b-daf58f6ac98d.png)

**Comment by desonx** [comment]
你好，你问我的这些我都不懂，你是在哪里看到我的邮箱地址的？是不是搞错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaitin/xray"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 下午2:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chaitin/xray] 请问crlf 注入功能如何使用 (Issue #1667)





 
我搭建了一个有crlf注入漏洞的靶场，
 
 当我用xray执行如下命令时却什么也没扫到
 xray --log-level debug ws --plugin crlf-injection -u http://10.0.0.131:8080/%0d%0aSet-Cookie:%20a=1

**Comment by HiJames93** [comment]
你好，我在GitHub上长亭的xray项目下留的言。不知道为什么会发到你的邮箱了。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月16日 14:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [chaitin/xray] 请问crlf 注入功能如何使用 (Issue #1667) |

你好，你问我的这些我都不懂，你是在哪里看到我的邮箱地址的？是不是搞错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chaitin/xray" ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 下午2:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chaitin/xray] 请问crlf 注入功能如何使用 (Issue #1667)






我搭建了一个有crlf注入漏洞的靶场，

当我用xray执行如下命令时却什么也没扫到
xray --log-level debug ws --plugin crlf-injection -u http://10.0.0.131:8080/%0d%0aSet-Cookie:%20a=1

**Comment by Jarcis-cy** [comment]
建议使用爬虫联动去扫描靶场试一下
