### ISSUE TITLE
请问phantasm插件的检测深度如何使用？

### ISSUE THREAD

**Issue by HiJames93** [chaitin/xray#1668]
不理解是phantasm插件的检测深度指的是扫描的链接深度还是什么意思？

**Comment by Jarcis-cy** [comment]
```
http://exmaple.com/     会执行, 上下文为 / 
http://example.com/a    不会再次执行，因为上下文同样为 /
http://example.com/a/b  会执行，上下文为 /a/
http://example.com/a/c/ 不会执行, 超过深度限制 (depth)
```

`depth` 是探测深度, 默认为 1, 即只在 URL 深度为 0, 和深度为 1 时运行该插件（前提是启用了该插件)

定义 http://example.com/，深度为 0，定义 http://example.com/a/, 深度为 1。 在这种配置下，dirscan 将对 

http://example.com/ 和 http://example.com/a/ 做两次扫描，如果存在 http://example.com/a/example.zip 那么就能将其扫描出来。
