### ISSUE TITLE
http配置中的 单个请求最大允许的跳转数 和 最大允许的响应大小 该怎么用？

### ISSUE THREAD

**Issue by HiJames93** [chaitin/xray#1669]

**Comment by Jarcis-cy** [comment]
**单个请求最大允许的跳转数**
有的时候，一个请求可能会产生一个重定向响应，然后这个响应又会产生一次请求，可能产生的请求所对应的响应又是一个重定向响应。这个时候，这个配置就可以限制这样套娃式的不断重定向的行为
**最大允许的响应大小**
这个是限制了返回包的大小，如果不限制，可能就导致一段时间内，一直在下载一个文件造成扫描效率降低等问题
