### ISSUE TITLE
Error:open module.xray.yaml: The system cannot find the file specified.

### ISSUE THREAD

**Issue by a1rtail** [chaitin/xray#1671]
启动xray时报错open module.xray.yaml: The system cannot find the file specified.请问该怎么解决

**Comment by WebFeng** [comment]
> 

配置文件是相对命令所在目录查找的，把命令拷贝到当前目录执行就可以了。

**Comment by Jarcis-cy** [comment]
新版本已经不存在这个问题了

**Comment by mayankmehra11** [comment]
config (xray.yaml) not found, gen xray.yaml/module.xray.yaml/plugin.xray.yaml .

It is still showing this. please help

**Comment by Jarcis-cy** [comment]
> config (xray.yaml) not found, gen xray.yaml/module.xray.yaml/plugin.xray.yaml .
> 
> It is still showing this. please help

What this means is that it's already been generated, so in theory it's good to run it again
