### ISSUE TITLE
use_comment_in_payload(在 payload 中使用 or)配置无效

### ISSUE THREAD

**Issue by maybe-why-not** [chaitin/xray#1672]
use_comment_in_payload: true，代理到burp
![image](https://user-images.githubusercontent.com/29968903/194518546-8aa6f98b-2926-4615-a643-f929f2038fb3.png)
没有payload里存在or的请求包
\?id=.*?[^a-z]or
![image](https://user-images.githubusercontent.com/29968903/194518998-9351a6e2-62d8-47de-bf31-99b9c31609c4.png)

**Comment by maybe-why-not** [comment]
1.9.3也扫不到or类型的sql注入

**Comment by Jarcis-cy** [comment]
不好意思,这个是配置文件的注释标注错误,这个实际上是开启后,在时间盲注的payload中添加comment关键词

**Comment by maybe-why-not** [comment]
> 不好意思,这个是配置文件的注释标注错误,这个实际上是开启后,在时间盲注的payload中添加comment关键词

问题是扫不到or类型的sql注入，sql注入的payload里没有or相关的请求包，配置文件的注释倒是其次

**Comment by Jarcis-cy** [comment]
目前xray确实没有使用or的相关payload,存在风险,取消掉了

**Comment by maybe-why-not** [comment]
> 

建议加到配置文件里，默认关闭

**Comment by Jarcis-cy** [comment]
已经没有or相关的payload了
