### ISSUE TITLE
open module.xray.yaml: The system cannot find the file specified.

### ISSUE THREAD

**Issue by HHasi** [chaitin/xray#1673]
open module.xray.yaml: The system cannot find the file specified. 请问如何解决

**Comment by Jarcis-cy** [comment]
在启动一次应该就会在本目录下生成相应配置文件

**Comment by kluo84** [comment]
Anyway we can put the xray executable file in /usr/local/bin and can call it everywhere without module.xray.yaml error???

**Comment by Jarcis-cy** [comment]
现在这个配置文件的生成的调用确实有点不合理，我们会在后续的版本中修复这个问题
