### ISSUE TITLE
浏览Youtube突然变慢

### ISSUE THREAD

**Issue by 3zhang** [chaitin/xray#1686]
有人有类似问题么？是不是Youtube走了什么别的协议绕开了代理？其他网站速度没问题

**Comment by Jarcis-cy** [comment]
可以查看xray的输出日志,看是否有相关的url,如果存在,可能并没有绕开代理,猜测是视频网站的原因?

现在还存在这个问题吗?出现问题的版本是什么呢?

**Comment by h3ak** [comment]
未复现成功

**Comment by JoJenH** [comment]
这哥们问的是另一个 xray，哭错坟了
