### ISSUE TITLE
Using listener got an tls error

### ISSUE THREAD

**Issue by abdilahrf** [chaitin/xray#1695]
Hi,

I got this problem when using xray as proxy listener `remote error: tls: user canceled`, I have installed the generated CA in my browser

![image](https://user-images.githubusercontent.com/6015012/206396882-d0881ad5-c03c-4178-b3d9-e967be99815b.png)

**Comment by Jarcis-cy** [comment]
You can confirm whether the upper layer of xray has an agent like burp. If it does, this problem may occur.
