### ISSUE TITLE
Crawling POST Parameters

### ISSUE THREAD

**Issue by Moskitoz** [chaitin/xray#1701]
Hello Developers,,

The Tool is great after many scans I've discover and be sure that the tool not crawl all parameters in pages specially the "parameters" in the "Filter Categories" most of this "Filters" are with POST requests

Here a live example for the Filter Categories

Step 1
https://i.ibb.co/0KNTH20/1.png

Step 2
https://i.ibb.co/y69q7x7/2.png

Step 3
https://i.ibb.co/YpD7vWJ/3.png

Hope my explain is clear and I hope the developer's find a solution to fix the crawl techniques to make the tool Crawl like this POST requests to make the tool extract more "parameters"

Best Regards,, and keep this tool UP!

**Comment by Jarcis-cy** [comment]
> github can actually upload images

I'm not sure what you mean. Do you want to analyze the parameters in the body of the post?
Maybe you can find an example website and describe what xray is doing on that site and what you want it to be doing.

**Comment by Jarcis-cy** [comment]
If you have new questions, welcome to continue to mention issue, we will actively reply to deal with!
