### ISSUE TITLE
配置文件检测路径问题

### ISSUE THREAD

**Issue by Bronya-Rayi** [chaitin/xray#1702]
必须在xray文件同路径下才能使用xray，否则会检测不到配置文件
![image](https://user-images.githubusercontent.com/47048823/209171727-d6cd95e0-8bcb-4cf7-86da-fa04393dc42e.png)
进入xray_dir路径后就能正常使用xray
![image](https://user-images.githubusercontent.com/47048823/209171839-376d1851-f8a8-467e-a2dd-bb7e899cffb3.png)

如果xray所在的位置有配置文件，在其他目录执行xray也会报错
![image](https://user-images.githubusercontent.com/47048823/209172172-e851ece9-ff31-4403-ad1d-2e7885bb6c14.png)

**Comment by Bronya-Rayi** [comment]
只有当前目录和xray所在目录都有配置文件的情况下才能正常启动，以前的xray默认是调用当前目录的配置文件，不知道是不是新版本做了什么修改

**Comment by Jarcis-cy** [comment]
后面版本会对这个问题进行修复

**Comment by akkuman** [comment]
相同的问题，版本 1.9.11
