### ISSUE TITLE
Scanning with Rate Limit

### ISSUE THREAD

**Issue by skalvin** [chaitin/xray#1703]
Can you please add a feature to the Xray Scanner to make it Scan with rate limit request for not to be blocked by WAF

**Comment by Jarcis-cy** [comment]
You can change the number of concurrent requests in the configuration file

**Comment by 4ra1n** [comment]
hello, we supper these params in config:
- parallel: number of POCs running simultaneously
- max_conns_per_host: maximum allowed connections for the same host
- max_qps: maximum requests per second
