### ISSUE TITLE
webhook扫描会报错，导致无法继续扫描

### ISSUE THREAD

**Issue by ltfafei** [chaitin/xray#1716]
使用场景：
![image](https://user-images.githubusercontent.com/43526141/220531166-da3ad633-d6c2-4819-8b48-e4874d15a183.png)

xray_linux_amd64 1.9.4最新版本

./xray_linux_amd64 ws --basic-crawler http://192.168.234.147:8983 --webhook-output http://x.x.x.x/webhook

![image](https://user-images.githubusercontent.com/43526141/220530879-18ceecb1-8b6c-4575-b0a6-6ba4bfb33cce.png)

**Comment by Jarcis-cy** [comment]
看起来好像是访问不到这个webhook了，但应该是不影响扫描的，这个应该是扫描结束了，可以打开debug模式观察一下输出

**Comment by ltfafei** [comment]
> 看起来好像是访问不到这个webhook了，但应该是不影响扫描的，这个应该是扫描结束了，可以打开debug模式观察一下输出

好的
