### ISSUE TITLE
如何关闭dirscan的子功能

### ISSUE THREAD

**Issue by z7701858** [chaitin/xray#1717]
如下dirscan的子功能影响较小，但是在大量目标中存在，可否在config中提供关闭选项
dirscan/sensitive/crossdomain
dirscan/debug/readme
dirscan/sourcemap/default
dirscan/config/ide

**Comment by Jarcis-cy** [comment]
1.9.4的xray的配置文件支持这个功能
![image](https://user-images.githubusercontent.com/39492464/223007992-57f7cbf8-64f0-4b75-9387-1985752d41bb.png)
