### ISSUE TITLE
关于爬虫和xray队列对接问题

### ISSUE THREAD

**Issue by p0desta** [chaitin/xray#1728]
你好,想问下xray有办法可以让外部爬虫拿到当前队列的数量么? 

文档中描述: "xray 将每 10s 打印一下当前任务队列长度，一旦堆积的数量达到 max_length，代理将会 “卡住”，新请求无法通过，等待队列中的请求被处理后再继续生效。默认配置的 10000 表示最多允许堆积 10000 个请求。"

我的理解是当队列满了之后,之后的请求不会再添加到队列,而爬虫仍然在运行,这里我有办法让爬虫拿到当前队列的数量吗？ 这样我就可以让爬虫不再生产请求了,从而避免漏掉很多URL。

**Comment by virusdefender** [comment]
webhook 中有输出

**Comment by p0desta** [comment]
@virusdefender 

感谢,已经拿到,webhook中num_found_urls-num_scanned_urls的数量就是pending的数量
