### ISSUE TITLE
反连平台生成的域名无效

### ISSUE THREAD

**Issue by ByCold** [chaitin/xray#1729]
配置了反连平台

DNS生成的域名ping不通的，需要排查哪里出现问题了呢

![image](https://user-images.githubusercontent.com/49861259/234199289-d2f53e06-6a1c-4430-a211-af11e4493624.png)

**Comment by Jarcis-cy** [comment]
请按照这个步骤完整的走一遍：https://docs.xray.cool/#/scenario/reverse
