### ISSUE TITLE
HTML或者webhook能输出所有扫描请求么？

### ISSUE THREAD

**Issue by peiyangL** [chaitin/xray#1738]
目前通过HTML或者webhook只会输出被确认为漏洞的请求，请让它输出所有扫过的请求信息么？

**Comment by virusdefender** [comment]
给 xray 加一个代理，在代理里面记录

**Comment by peiyangL** [comment]
> 给 xray 加一个代理，在代理里面记录

但是这样应该只能记录raw request，不像xray的report可以把攻击payload位置等信息都记录下来？
