### ISSUE TITLE
webhook能和文件一起输出吗？

### ISSUE THREAD

**Issue by PhuketIsland** [chaitin/xray#1741]
目前使用webhook的方式进行输出，但是我还想本地再保留一份
![image](https://github.com/chaitin/xray/assets/28825226/dbbbcc40-edd7-4aee-8f7e-98b7d19bd4e5)
--webhook-output http://usb:5005/api/v1/xray     
--html-output proxy.html
怎么能将这两种输出方式在一次代理扫描中同时输出呢？

**Comment by Jarcis-cy** [comment]
理论上都加上就好了，都会输出的
