### ISSUE TITLE
安卓模拟器安装xray-CA证书失败

### ISSUE THREAD

**Issue by Sec-Love** [chaitin/xray#1742]
我使用xray代理模式监听来自安卓app的https流量，需要在安卓的系统证书中安装xray的CA证书，我使用openssl计算了ca证书的hash值，然后将{hash}.0文件push到安装设备的/system/etc/security/cacerts中，但是安装不起作用，我使用同样的方法安装yakit的证书成功，并且使用yakit成功捕获到安卓app的https请求？有人遇到同样的问题吗，该如何解决？

**Comment by Jlan45** [comment]
https://docs.xray.cool/tools/xray/Scanning
已更新模块添加CA证书方式
https://github.com/Jlan45/xray-CA-cert-module

**Comment by soshunte** [comment]
https://docs.xray.cool/tools/xray/Scanning
已更新模块添加CA证书方式
https://github.com/Jlan45/xray-CA-cert-module  请问下这个模块是直接安装在面具就可以了吗？是否需要在电脑端的crt改成cer在手机上安装呢
