### ISSUE TITLE
xray与burp联动时，显示无法从服务器接收响应包,

### ISSUE THREAD

**Issue by RunfarZhang** [chaitin/xray#1751]
![image](https://github.com/chaitin/xray/assets/37327252/c70ef997-433b-4a60-80f0-021ec2407cf6)
xray version：1.9.11
burp version：2023.9.4

**Comment by ctxer** [comment]
同样问题，后来解决了吗？

**Comment by RunfarZhang** [comment]
把默认的http2关掉解决了~~
