### ISSUE TITLE
Archlinux

### ISSUE THREAD

**Issue by aaddmin1122345** [chaitin/xray#1753]
./xray_linux_amd64: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory

无法启动

**Comment by lxmcs** [comment]
find /usr -name 'libpcap.so*'
找到文件后，如果你发现有libpcap.so.1而不是libpcap.so.0.8，你可以创建一个软链接，让系统认为libpcap.so.0.8也存在。例如，如果你找到的是libpcap.so.1，可以用下面的命令创建一个链接：
sudo ln -s /usr/lib/libpcap.so.1 /usr/lib/libpcap.so.0.8
请确保将/usr/lib/libpcap.so.1替换成你实际找到的libpcap库的路径。

如果没有找该库需要 sudo pacman -S libpcap 先安装一下 然后根据实际位置 做软连

**Comment by V0WKeep3r** [comment]
查看/usr/lib64目录下的 libpcap.so.* 文件，发现libpcap.so和libpcap.so.1都是libpcap.so.1.9.1的软链接文件。只需要在/usr/lib64/目录下再建一个软链接文件就能成功解决问题了。
```bash
ls -al /usr/lib64/libpcap.so.*
ln -s libpcap.so.1.9.1 libpcap.so.0.8
```

<img width="889" alt="image" src="https://github.com/chaitin/xray/assets/78677532/64104c64-b1c0-4f47-ae82-e9759efdc2ba">

**Comment by V0WKeep3r** [comment]
> ./xray_linux_amd64: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory
> 
> 无法启动

查看/usr/lib64目录下的 libpcap.so.* 文件，发现libpcap.so和libpcap.so.1都是libpcap.so.1.9.1的软链接文件。只需要在/usr/lib64/目录下再建一个软链接文件就能成功解决问题了。
```bash
ls -al /usr/lib64/libpcap.so.*
ln -s libpcap.so.1.9.1 libpcap.so.0.8
```

<img width="889" alt="image" src="https://github.com/chaitin/xray/assets/78677532/64104c64-b1c0-4f47-ae82-e9759efdc2ba">
