### ISSUE TITLE
1.9.11版本扫描报错

### ISSUE THREAD

**Issue by Hel10-Web** [chaitin/xray#1760]
![image](https://github.com/chaitin/xray/assets/54520809/ce3bd72f-01d5-4875-ab26-adf39eef6e02)

**Comment by Hel10-Web** [comment]
配置文件错误引起的

**Comment by 4ra1n** [comment]
看一下你的反连平台配置

**Comment by Jarcis-cy** [comment]
如果还有问题，可以提新的issue
