### ISSUE TITLE
请问当前版本（1.9.11）怎么设置 upstream_proxy参数？

### ISSUE THREAD

**Issue by YiZoo** [chaitin/xray#1763]
我想把xray的流量转发到其他工具上，当前版本的配置文件该怎么设置upstream_proxy参数，请师傅得空时指教，非常感谢！！

**Comment by Jarcis-cy** [comment]
配置文件第八行就是
![image](https://github.com/chaitin/xray/assets/39492464/4bcc6b87-e628-4cb6-8728-c2dea821a9f7)

**Comment by YiZoo** [comment]
![xray_run_sc](https://github.com/chaitin/xray/assets/137678543/d0ef88ef-eab0-4efd-b120-8f3d5e45d3c9)
首次运行没有生成config文件，我该怎么配置该文件呢

**Comment by YiZoo** [comment]
执行其他操作时，又自动生成了配置文件，问题已解决
