### ISSUE TITLE
Problem with upgrade?!

### ISSUE THREAD

**Issue by TannicArcher** [chaitin/xray#1764]
./xray_linux_amd64 upgrade
Version: 1.9.11/eb0c331d/COMMUNITY

check update failed, err: invalid character 'i' looking for beginning of value
invalid character 'i' looking for beginning of value
What problem?

System Ubuntu Ubuntu 23.10 mantic

**Comment by Jarcis-cy** [comment]
At present, this is the latest version of xray. If you want to experience xray2.0 related content, you can try [xpoc](https://github.com/chaitin/xpoc)

This update actually uses a cloud function for detection. Because the information on the cloud function is not updated, problems may occur.

**Comment by TannicArcher** [comment]
Ok thanks
