### ISSUE TITLE
如何通过命令行设置cookie参数？

### ISSUE THREAD

**Issue by 4ooooo** [chaitin/xray#1778]
如题，在测一个wordpress站的时候拿到了弱口令，想把cookie加到xray上扫。cookie一共三个字段，往config.yaml里加，example只给了一个字段的示例。通过命令行加不知道行不行

**Comment by Jarcis-cy** [comment]
https://docs.xray.cool/tools/xray/Configuration#http
cookie正常在配置文件中添加即可，不支持命令行添加

或者可以使用被动代理的形式进行扫描
