### ISSUE TITLE
Reverse server configuration with ngrok tcp 1337

### ISSUE THREAD

**Issue by mjulda** [chaitin/xray#1792]
[INFO] 2024-04-29 11:01:08 [phantasm:phantasm.go:185] 819 pocs have been loaded (debug level will show more details)
These plugins will be disabled as reverse server is not configured, check out the reference to fix this error.
Ref: https://docs.xray.cool/#/configration/reverse
Plugins:

I've looked at the configuration guide but I don't understand how to connect with ngrok.
Anyone want to help me?😥😪

**Comment by mjulda** [comment]
Dari file module.xray.yaml

Reverse:
    client:
        dns_server_ip: ""
        http_base_url: ""
        remote_server: false
        reverse_api: ""
        reverse_server_url: ""
        rmi_server_addr: ""
    db_file_path: ""
    dns:
        domain: ""
        enabled: false
        is_domain_name_server: false
        listen_ip: 0.0.0.0
        resolve:
            - record: localhost
              ttl: 60
              type: A
              value: 127.0.0.1
    http:
        enabled: false
        ip_header: ""
        listen_ip: 0.0.0.0
        listen_port: ""
    rmi:
        enabled: false
        listen_ip: 127.0.0.1
        listen_port: ""
    token: ""

============================
how to connect with ngrok.

Version                       3.8.0 
Region                        Asia Pacific (ap)
Web Interface             http://127.0.0.1:4040                                                                     
Forwarding                 tcp://0.tcp.ap.ngrok.io:17537 -> localhost:1337                                                                                                                                                                   Connections               ttl     opn     rt1     rt5     p50     p90  
                                   0       0       0.00    0.00    0.00    0.00

**Comment by Jarcis-cy** [comment]
If you want to use a backlink to an extranet on the intranet, ngrok as an intranet penetration should theoretically be the content of the proxy at a higher level, independent of the configuration of the xray itself.

**Comment by Jarcis-cy** [comment]
Recommended reading of this document: https://docs.xray.cool/tools/xray/advanced/reverse

Available: https://immersivetranslate.com/
This browser plugin does a great job of translating!
