### ISSUE TITLE
xray_darwin_arm64文件执行，缺少xray.yaml文件，程序无法运行，能否给个 对应的yaml文件

### ISSUE THREAD

**Issue by wangyan2024** [chaitin/xray#1794]
<img width="873" alt="image" src="https://github.com/chaitin/xray/assets/166290401/7602ae68-1477-4aa1-b6d3-b60ff99d7f5d">
<img width="1031" alt="image" src="https://github.com/chaitin/xray/assets/166290401/7f04241d-d1fe-48ac-b959-e110bbee3648">

**Comment by Jarcis-cy** [comment]
理论上会自动生成

**Comment by Mengter8** [comment]
> 理论上会自动生成

遇到同样的问题，必须cd到xray的目录才能正常识别配置文件
