### ISSUE TITLE
扫描速度慢但浏览时网络良好

### ISSUE THREAD

**Issue by ghost** [chaitin/xray#1796]
网络良好，默认DNS，已改为Google DNS，防火墙关闭。但扫描时速度慢

┌──(shiro㉿kali)-[~/BugBounty]
└─$ ping website.com
PING website.com (2X2.70.XXX.4) 56(84) bytes of data.
64 bytes from website.com (2X2.70.XXX.4): icmp_seq=1 ttl=247 time=52.6 ms
64 bytes from website.com (2X2.70.XXX.4): icmp_seq=2 ttl=247 time=53.6 ms
64 bytes from website.com (2X2.70.XXX.4): icmp_seq=3 ttl=247 time=54.4 ms
64 bytes from website.com (2X2.70.XXX.4): icmp_seq=4 ttl=247 time=53.6 ms
64 bytes from website.com (2X2.70.XXX.4): icmp_seq=5 ttl=247 time=53.0 ms
64 bytes from website.com (2X2.70.XXX.4): icmp_seq=6 ttl=247 time=53.7 ms

[] scanned: 117, pending: 9, requestSent: 5766, latency: 3646.97ms, failedRatio: 0.09%
[INFO] 2024-05-14 07:35:34 [default:dispatcher.go:444] processing GET https://website.com/id/layanan/psc-119
[*] scanned: 117, pending: 10, requestSent: 5786, latency: 3485.15ms, failedRatio: 0.09%
[INFO] 2024-05-14 07:35:40 [default:dispatcher.go:444] processing GET https://website.com/id/profil-pejabat/dante-saksono-harbuwono
[*] scanned: 117, pending: 11, requestSent: 5803, latency: 3972.14ms, failedRatio: 0.09%
[*] scanned: 117, pending: 11, requestSent: 5807, latency: 4029.27ms, failedRatio: 0.09%
[INFO] 2024-05-14 07:35:46 [default:dispatcher.go:444] processing GET https://farmalkes.website.com/2024/05/terapi-sel-punca-inovasi-baru-dalam-pengobatan-penyakit/
[INFO] 2024-05-14 07:35:46 [default:dispatcher.go:444] processing GET https://website.com/eng/rilis-kesehatan/presiden-jokowi-tekankan-pentingnya-layanan-stroke-dan-jantung-di-rsud
[INFO] 2024-05-14 07:35:47 [default:dispatcher.go:444] processing GET https://website.com/id/category/infarkes
[*] scanned: 117, pending: 14, requestSent: 5842, latency: 4246.01ms, failedRatio: 0.09%
[*] scanned: 117, pending: 14, requestSent: 5859, latency: 4654.39ms, failedRatio: 0.09%
[*] scanned: 117, pending: 14, requestSent: 5880, latency: 4759.56ms, failedRatio: 0.09%
[*] scanned: 117, pending: 14, requestSent: 5892, latency: 5139.73ms, failedRatio: 0.08%
[*] scanned: 117, pending: 14, requestSent: 5915, latency: 5105.25ms, failedRatio: 0.08%
[*] scanned: 117, pending: 14, requestSent: 5934, latency: 4820.95ms, failedRatio: 0.08%
[*] scanned: 119, pending: 12, requestSent: 5958, latency: 4379.07ms, failedRatio: 0.08%
[*] scanned: 121, pending: 10, requestSent: 5979, latency: 3864.66ms, failedRatio: 0.08%
[*] scanned: 122, pending: 9, requestSent: 5995, latency: 3439.34ms, failedRatio: 0.08%
[*] scanned: 122, pending: 9, requestSent: 6010, latency: 3101.25ms, failedRatio: 0.08%
[*] scanned: 123, pending: 8, requestSent: 6026, latency: 2528.44ms, failedRatio: 0.08%
[*] scanned: 124, pending: 7, requestSent: 6032, latency: 2487.37ms, failedRatio: 0.08%
[*] scanned: 124, pending: 7, requestSent: 6044, latency: 2400.43ms, failedRatio: 0.08%
[*] scanned: 124, pending: 7, requestSent: 6057, latency: 2481.83ms, failedRatio: 0.08%
[*] scanned: 125, pending: 6, requestSent: 6071, latency: 2457.54ms, failedRatio: 0.08%

**Comment by Jarcis-cy** [comment]
requestSent是发包数，看起来是在正常扫描呀

**Comment by Shiroxzgod** [comment]
> requestSent是发包数，看起来是在正常扫描呀

ただし、速度が遅いように見えますが、インターネット ネットワークはスムーズです

**Comment by Shiroxzgod** [comment]
> requestSent是发包数，看起来是在正常扫描呀

ただし、速度が遅いように見えますが、インターネット ネットワークはスムーズです

**Comment by Jarcis-cy** [comment]
可能就是插件启动比较多导致的，可以自己写一个服务，扫描一下看看就知道了

**Comment by Shiroxzgod** [comment]
> 可能就是插件启动比较多导致的，可以自己写一个服务，扫描一下看看就知道了

スキャン中に別の問題が発生しました。ブラウザでエラー コード ERR_CONNECTION_TIMEOUT が表示され、対象の Web サイトを開くことができません。WiFi ルーターを再起動するか ネットワークを変更すると、Android にも影響があり、対象の Web サイトを開けなくなります。セルラーデータまたは別の WiFi 接続に変更すると開くことができます

**Comment by Jesselynz** [comment]
![Screenshot_2024-05-18_21_57_49](https://github.com/chaitin/xray/assets/58801545/6e460477-f7e5-49f9-bea6-703991d6c858)

自分自身をブロックしました

**Comment by Jarcis-cy** [comment]
> > 可能就是插件启动比较多导致的，可以自己写一个服务，扫描一下看看就知道了
> 
> スキャン中に別の問題が発生しました。ブラウザでエラー コード ERR_CONNECTION_TIMEOUT が表示され、対象の Web サイトを開くことができません。WiFi ルーターを再起動するか ネットワークを変更すると、Android にも影響があり、対象の Web サイトを開けなくなります。セルラーデータまたは別の WiFi 接続に変更すると開くことができます

これはおそらく、あなたが向こうから追放されたからでしょう。

**Comment by Jarcis-cy** [comment]
スキャン自体が攻撃と似ているため、あなたのipやその他の特徴が相手によってブラックリストに登録されている可能性がある。

**Comment by r0x5r** [comment]
same thing happend with me idont now the exact problem but it should need to be  patched also now update a new version of this software
