### ISSUE TITLE
第一次用，为什么会出现自动连接本地代理？

### ISSUE THREAD

**Issue by gududezoumingqu** [chaitin/xray#1797]
<img width="866" alt="2024-05-17_152625" src="https://github.com/chaitin/xray/assets/134898787/b07e0be9-cd92-4c57-ab66-933dd4b1c9ff">
<img width="866" alt="2024-05-17_152625" src="https://github.com/chaitin/xray/assets/134898787/8985780b-5e9f-4dfc-8a22-0c9a56244011">

**Comment by chinaykc** [comment]
发送请求的过程会读取环境变量中的代理信息
