### ISSUE TITLE
Crawler here in the profile, what is the role of configuring the username and password, set and not set the feeling is the same, and when I set the user and password it will not use this user and password to log in

### ISSUE THREAD

**Issue by lsota1** [chaitin/xray#1798]
Crawler here in the profile, what is the role of configuring the username and password, set and not set the feeling is the same, and when I set the user and password it will not use this user and password to log in

![image](https://github.com/chaitin/xray/assets/155864641/015116d1-1fe6-4828-a0ed-f6032d7fd4ab)

**Comment by Jarcis-cy** [comment]
It's not recommended to use this way of scanning, it's better to use [rad](https://github.com/chaitin/rad) with xray, then just configure the login in [rad](https://github.com/chaitin/rad), or xray just turn on passive and login manually
