### ISSUE TITLE
SQL注入 误报

### ISSUE THREAD

**Issue by ic3z** [chaitin/xray#18]
举个例子

```
./xray_linux_amd64  webscan  --plugins sqldet --url "http://xxxx.qq.com/qunvideo/hall.html?_bid=2227&_wv=5127&from=tuijian_more"
```

![image](https://user-images.githubusercontent.com/24785607/60674958-e03aee00-9ead-11e9-95fd-9d633c0e832f.png)

![image](https://user-images.githubusercontent.com/24785607/60675110-3314a580-9eae-11e9-9c36-a0c66aabf98f.png)

**Comment by virusdefender** [comment]
0.5.1 修了，麻烦再试试

https://github.com/chaitin/xray/releases
