### ISSUE TITLE
reverse模式下，开放端口了也会提示init reverse server error: health check failed for remote reverse server, error: Get "http://ip:8988/_/api/health_check": dial tcp ip:8988: connect: connection refused

### ISSUE THREAD

**Issue by aba666666** [chaitin/xray#1801]
reverse:
  db_file_path: "/tmp/xray.db"                      # 反连平台数据库文件位置, 这是一个 KV 数据库
  token: "XXX"                             # 反连平台认证的 Token, 独立部署时不能为空
  http:
    enabled: true
    listen_ip: 0.0.0.0 
    listen_port: "8988"
    ip_header: ""                       # 在哪个 http header 中取 ip，为空代表从 REMOTE_ADDR 中取
  dns:
    enabled: false
    listen_ip: 0.0.0.0 
    domain: ""                          # DNS 域名配置
    is_domain_name_server: false        # 是否修改了域名的 ns 为反连平台，如果是，那 nslookup 等就不需要指定 dns 了
    resolve:                            # DNS 静态解析规则
    - type: A                           # A, AAAA, TXT 三种
      record: localhost
      value: 127.0.0.1
      ttl: 60
  client:
    remote_server: true                # 是否是独立的远程 server，如果是要在下面配置好远程的服务端地址
    http_base_url: "http://ip:8988"                   # 默认将根据 ListenIP 和 ListenPort 生成，该地址是存在漏洞的目标反连回来的地址, 当反连平台前面有反代、绑定域名、端口映射时需要自行配置
    dns_server_ip: ""                   # 和 http_base_url 类似，实际用来访问 dns 服务器的地址

**Comment by aba666666** [comment]
![image](https://github.com/chaitin/xray/assets/113227651/ba3f9bc4-9df5-423a-bf65-fd615ca17684)

**Comment by 4ra1n** [comment]
remote_server: false 
试试

**Comment by lyangdn** [comment]
remote_server: true 
改成false，这是客户端的

**Comment by RobustBody** [comment]
服务器端，不要配置client:remote_server: true，改为false
