### ISSUE TITLE
优化建议能添加一个plugins-Lack of Authentication吗。

### ISSUE THREAD

**Issue by 0neAtSec** [chaitin/xray#1814]
就是被动扫描时，对接口自动删除这些Cookie/Authorization/Token头的认证信息。测试未授权访问。可以自己设置删除哪些头。对比两个包的返回长度。
同理 如果替换不同权限的认证信息，能否扫描出越权漏洞呢。

**Comment by Jarcis-cy** [comment]
1. 自动化测试会比较难做，因为你并不能知道当没有认证信息的时候，对方的反应是什么，只能够猜测，401或403等，相对来说会比较容易误报，不过或许可以作为提示
2. 商业版的xray已经支持扫描越权漏洞

**Comment by Jarcis-cy** [comment]
且第一个商业版也存在相应的扫描插件，但效果确实很难保证准确，受制于原理，非常需要抠细节

**Comment by 0neAtSec** [comment]
确实扫描的效果需要人工介入。自动化扫描误报率太多QAQ
