### ISSUE TITLE
可否支持更细粒度的目标配置

### ISSUE THREAD

**Issue by linpengstc** [chaitin/xray#19]
被动扫描能否支持这样的场景：会员业务 taodao.com/user  商品业务taodao.com/item，可能安全测试时仅仅想针对商品业务进行测试，希望被动扫描只针对taodao.com/item下的url进行扫描

当前的被动扫描似乎只能控制到域名级别

**Comment by virusdefender** [comment]
已加，等下个版本。

**Comment by virusdefender** [comment]
欢迎升级试用

https://github.com/chaitin/xray/releases/tag/0.6.0
