### ISSUE TITLE
cli请求url返回403/404之类的，但是xray代理后报tcp dial io timeout，这是网络连接超时还是http状态码不对也会这么报错？

### ISSUE THREAD

**Issue by tuhaolam** [chaitin/xray#21]
<img width="1279" alt="xray_issue01" src="https://user-images.githubusercontent.com/10894348/60791629-a4967180-a196-11e9-91af-9d177e5d397e.png">

**Comment by zema1** [comment]
可能是 waf ?

**Comment by zema1** [comment]
尝试降低 `max_qps`

**Comment by virusdefender** [comment]
先 close 了，有问题可以随时回复。
