### ISSUE TITLE
建议配置文件可以增加一个网站编程语言的配置选项

### ISSUE THREAD

**Issue by shmilylty** [chaitin/xray#23]
建议配置文件可以增加一个网站编程语言的配置选项可以是dirscan发出的请求更有针对性，如果一个php写的网站发一些x.jsp x.asp x.aspx的请求不仅没用还增加了服务器的响应压力。（除了文件后缀不同的编程语言写的网站目录都还有一些其他的特征，针对不同的语言可以使用不同的字典最好）

**Comment by zema1** [comment]
是一个可行的优化想法，但目前不是一个高优先级的目标，待稳定了会进行这方面的工作的。 感谢反馈。

**Comment by Jarcis-cy** [comment]
感谢您的反馈，我们内部已对此进行了相关的实现，未来将会在的xray 2.0系列中的产品中体验到
