### ISSUE TITLE
漏洞结果可以放在最后面么

### ISSUE THREAD

**Issue by neal1991** [chaitin/xray#25]
可以把漏洞结果放在最后面，或者直接在最后面做一个总结，在命令行中很容易被滚掉

**Comment by monstersb** [comment]
可以输出到中间里呀。
   --text-output FILE  output xray result to FILE in plain text format
   --json-output FILE  output xray result to FILE in json format
   --html-output FILE  output xray result to FILE in HTML format

**Comment by neal1991** [comment]
就是也不想输出到文件

**Comment by virusdefender** [comment]
现在只有 json 文件可以保证是安全的，stdout 容易滚没了，html 文件是最后才写的，一旦 crash 就没了，如果最后输出到 stdout 也是同理。
