### ISSUE TITLE
SQL注入误报

### ISSUE THREAD

**Issue by ADOOO** [chaitin/xray#27]
![is-1](https://user-images.githubusercontent.com/11754811/61074605-a8eab500-a44a-11e9-8a90-9129a3c51bd8.jpg)
![is-2](https://user-images.githubusercontent.com/11754811/61074611-abe5a580-a44a-11e9-8d46-36cc4b8f09f3.jpg)

**Comment by ADOOO** [comment]
判断注入时用到了如下payload：
http://x.com/1.php?id=1*1
http://x.com/1.php?id=1/1

页面返回内容一致即认为有注入，如此判断造成误报

**Comment by virusdefender** [comment]
这个可能是因为后端有 cast 导致的，sql 布尔盲注怎么去验证漏洞已经在考虑了。

**Comment by virusdefender** [comment]
麻烦给一个完整的漏洞 json 吧，图上信息有点少。

**Comment by ADOOO** [comment]
here:
`{
    "create_time": 1562868081062,
    "detail": {
        "payload": "1/0",
        "request1": {
            "raw_body": "",
            "raw_header": "GET /orderapi/pchome/getHomePopularityRecommend.do?_=1562868005512\u0026type=1%2A1 HTTP/1.1\r\nHost: xxx.com.cn:443\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169\r\nAccept: */*\r\nAccept-Language: zh-CN,zh;q=0.9,en;q=0.8\r\nCookie: key=value\r\nOrigin: https://xxx.com.cn\r\nReferer: https://xxx.com.cn/i/coupon\r\nAccept-Encoding: gzip\r\n\r\n"
        },
        "request2": {
            "raw_body": "",
            "raw_header": "GET /orderapi/pchome/getHomePopularityRecommend.do?_=1562868005512\u0026type=1%2F0 HTTP/1.1\r\nHost: xxx.com.cn:443\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169\r\nAccept: */*\r\nAccept-Language: zh-CN,zh;q=0.9,en;q=0.8\r\nCookie: key=value\r\nOrigin: https://xxx.com.cn\r\nReferer: https://xxx.com.cn/i/coupon\r\nAccept-Encoding: gzip\r\n\r\n"
        },
        "response1": {
            "raw_body": "{\"message\":\"获取成功\",\"result\":[{\"Status\":false,\"Price\":126.0000,\"ItemTitle\":\"小米移动电源2C 20000mAh\",\"PicPath\":\"//img2.autoimg.cn/hscdfs/g29/M08/26/F1/autohomecar__ChsEfly22AWAOzmNAABdgwNwdxg746.jpg\",\"CreateTime\":1559554665877,\"SPU\":15417,\"RecommendWord\":\"大容量 一个就够用\",\"Id\":3036},{\"Status\":false,\"Price\":129.0000,\"ItemTitle\":\"车玛仕枪神五合一充气泵（黑色家车两用款）\",\"PicPath\":\"//wz0.autoimg.cn/g25/M03/61/CD/ChcCr1psHmyARhULAAEEUpAUPvs661.jpg\",\"CreateTime\":1559554891943,\"SPU\":2972,\"RecommendWord\":\"功能五合一 三色可选\",\"Id\":3037},{\"Status\":false,\"Price\":69.0000,\"ItemTitle\":\"米其林分解型空气除味剂\",\"PicPath\":\"//img2.autoimg.cn/hscdfs/g2/M03/7B/80/autohomecar__ChsEkFyTRKKAG4VdAABFB7w80kU495.jpg\",\"CreateTime\":1559555285700,\"SPU\":15309,\"RecommendWord\":\"天然植物分解型 车家两用\",\"Id\":3038},{\"Status\":false,\"Price\":198.0000,\"ItemTitle\":\"悦卡36升电动洗车机（单泵）\",\"PicPath\":\"//wz0.autoimg.cn/g24/M08/13/CC/ChcCL1p4RPmAYy1bAAEHSKiOxxY651.jpg\",\"CreateTime\":1559555526227,\"SPU\":3129,\"RecommendWord\":\"省时/省力/更省钱\",\"Id\":3039},{\"Status\":false,\"Price\":159.0000,\"ItemTitle\":\"卡饰社快速凉风坐垫窄版款\",\"PicPath\":\"//wz0.autoimg.cn/g1/M03/3E/62/wKgHGFtpDkqAbA_aAAEWQo3Y870334.jpg\",\"CreateTime\":1559556817027,\"SPU\":4898,\"RecommendWord\":\"快速降温 拒绝闷热\",\"Id\":3040},{\"Status\":false,\"Price\":79.0000,\"ItemTitle\":\"乔氏元宝记忆棉颈枕-打孔皮革款（优雅咖）\",\"PicPath\":\"//wz0.autoimg.cn/g28/M01/0A/FE/wKgHI1tQZyKAWTspAACUXZx-2kQ747.jpg\",\"CreateTime\":1559557042867,\"SPU\":4774,\"RecommendWord\":\"让驾驶成为一种享受\",\"Id\":3041},{\"Status\":false,\"Price\":89.0000,\"ItemTitle\":\"AirFunk天然空气净化剂甲醛清除剂（经典绿箭）\",\"PicPath\":\"//wz0.autoimg.cn/g24/M0A/8F/0C/ChcCL1rkN1aAQJdpAAETE3-JjDc097.jpg\",\"CreateTime\":1559557296003,\"SPU\":3944,\"RecommendWord\":\"可覆盖45m² 持续1～3个月\",\"Id\":3042},{\"Status\":false,\"Price\":78.0000,\"ItemTitle\":\"3M浓缩雨刷精（5瓶装）\",\"PicPath\":\"//wz0.autoimg.cn/g30/M08/4B/94/ChcCSVvyrqqAIw4ZAADbaQ2YcJo773.jpg\",\"CreateTime\":1559557452980,\"SPU\":5635,\"RecommendWord\":\"一喷一刮 视野清晰\",\"Id\":3043}],\"returncode\":0}",
            "raw_header": "HTTP/1.1 200 \r\nAccess-Control-Allow-Credentials: true\r\nAccess-Control-Allow-Origin: https://xxx.com.cn\r\nConnection: keep-alive\r\nContent-Disposition: inline;filename=f.txt\r\nContent-Type: application/json;charset=UTF-8\r\nDate: Thu, 11 Jul 2019 18:01:17 GMT\r\nServer: 5.63\r\nStrict-Transport-Security: max-age=31622400\r\n"
        },
        "response2": {
            "raw_body": "{\"message\":\"获取成功\",\"result\":[{\"Status\":false,\"Price\":126.0000,\"ItemTitle\":\"小米移动电源2C 20000mAh\",\"PicPath\":\"//img2.autoimg.cn/hscdfs/g29/M08/26/F1/autohomecar__ChsEfly22AWAOzmNAABdgwNwdxg746.jpg\",\"CreateTime\":1559554665877,\"SPU\":15417,\"RecommendWord\":\"大容量 一个就够用\",\"Id\":3036},{\"Status\":false,\"Price\":129.0000,\"ItemTitle\":\"车玛仕枪神五合一充气泵（黑色家车两用款）\",\"PicPath\":\"//wz0.autoimg.cn/g25/M03/61/CD/ChcCr1psHmyARhULAAEEUpAUPvs661.jpg\",\"CreateTime\":1559554891943,\"SPU\":2972,\"RecommendWord\":\"功能五合一 三色可选\",\"Id\":3037},{\"Status\":false,\"Price\":69.0000,\"ItemTitle\":\"米其林分解型空气除味剂\",\"PicPath\":\"//img2.autoimg.cn/hscdfs/g2/M03/7B/80/autohomecar__ChsEkFyTRKKAG4VdAABFB7w80kU495.jpg\",\"CreateTime\":1559555285700,\"SPU\":15309,\"RecommendWord\":\"天然植物分解型 车家两用\",\"Id\":3038},{\"Status\":false,\"Price\":198.0000,\"ItemTitle\":\"悦卡36升电动洗车机（单泵）\",\"PicPath\":\"//wz0.autoimg.cn/g24/M08/13/CC/ChcCL1p4RPmAYy1bAAEHSKiOxxY651.jpg\",\"CreateTime\":1559555526227,\"SPU\":3129,\"RecommendWord\":\"省时/省力/更省钱\",\"Id\":3039},{\"Status\":false,\"Price\":159.0000,\"ItemTitle\":\"卡饰社快速凉风坐垫窄版款\",\"PicPath\":\"//wz0.autoimg.cn/g1/M03/3E/62/wKgHGFtpDkqAbA_aAAEWQo3Y870334.jpg\",\"CreateTime\":1559556817027,\"SPU\":4898,\"RecommendWord\":\"快速降温 拒绝闷热\",\"Id\":3040},{\"Status\":false,\"Price\":79.0000,\"ItemTitle\":\"乔氏元宝记忆棉颈枕-打孔皮革款（优雅咖）\",\"PicPath\":\"//wz0.autoimg.cn/g28/M01/0A/FE/wKgHI1tQZyKAWTspAACUXZx-2kQ747.jpg\",\"CreateTime\":1559557042867,\"SPU\":4774,\"RecommendWord\":\"让驾驶成为一种享受\",\"Id\":3041},{\"Status\":false,\"Price\":89.0000,\"ItemTitle\":\"AirFunk天然空气净化剂甲醛清除剂（经典绿箭）\",\"PicPath\":\"//wz0.autoimg.cn/g24/M0A/8F/0C/ChcCL1rkN1aAQJdpAAETE3-JjDc097.jpg\",\"CreateTime\":1559557296003,\"SPU\":3944,\"RecommendWord\":\"可覆盖45m² 持续1～3个月\",\"Id\":3042},{\"Status\":false,\"Price\":78.0000,\"ItemTitle\":\"3M浓缩雨刷精（5瓶装）\",\"PicPath\":\"//wz0.autoimg.cn/g30/M08/4B/94/ChcCSVvyrqqAIw4ZAADbaQ2YcJo773.jpg\",\"CreateTime\":1559557452980,\"SPU\":5635,\"RecommendWord\":\"一喷一刮 视野清晰\",\"Id\":3043}],\"returncode\":0}",
            "raw_header": "HTTP/1.1 200 \r\nAccess-Control-Allow-Credentials: true\r\nAccess-Control-Allow-Origin: https://xxx.com.cn\r\nConnection: keep-alive\r\nContent-Disposition: inline;filename=f.txt\r\nContent-Type: application/json;charset=UTF-8\r\nDate: Thu, 11 Jul 2019 18:01:17 GMT\r\nServer: 5.63\r\nStrict-Transport-Security: max-age=31622400\r\n"
        },
        "target": {
            "param": {
                "key": "type",
                "position": "query",
                "value": "1/0"
            },
            "url": "https://xxx.com.cn:443/orderapi/pchome/getHomePopularityRecommend.do?type=1\u0026_=1562868005512"
        }
    },
    "plugin": "sqldet",
    "vuln_class": ""
},`

**Comment by virusdefender** [comment]
再试试新版呢？有问题可以新开 issue，感谢~
