### ISSUE TITLE
关于config配置过滤域名的问题

### ISSUE THREAD

**Issue by 7e1** [chaitin/xray#29]
includes: # 允许扫描的域
      - "*.example.com"

可以配置多个子域名么？

>  (.*?)\.(a|b)\.example\.com

-  test.a.example.com
-  test.b.example.com

>  (.*?)\.(example1|example2)\.com

-  test.example1.com
-  test.example2.com

**Comment by virusdefender** [comment]
直接写多个精确匹配可以么

**Comment by 7e1** [comment]
> 直接写多个精确匹配可以么
一行只能匹配单个域名*.a.example.com 感觉太麻烦了。会有很多域名。  不清楚你们这个正则是怎么处理的。 我在burp上看到是可以一行匹配多个么？类似(.*?).(example1|example2).com  或者(.*?).(a|b).example.com 这样匹配起来就很简单了。

**Comment by virusdefender** [comment]
写成四个应该可以吧

```
*.[ab].example.com
[ab].example.com
*.example1.com
*.example2.com
```

可以来这里测试一下 http://www.globtester.com/

**Comment by 7e1** [comment]
> 写成四个应该可以吧
> 
> ```
> *.[ab].example.com
> [ab].example.com
> *.example1.com
> *.example2.com
> ```
> 
> 可以来这里测试一下 http://www.globtester.com/

这样可以了。 谢谢。

**Comment by 7e1** [comment]
可以这样么?
@(atest|btest).example.com
我在globtester.com上是可以解析成
-  atest.example.com
-  btest.example.com

但是在config里面配置excludes的时候
\-  "@(atest|btest).example.com"就无法解析了。

**Comment by 7e1** [comment]
> 写成四个应该可以吧
> 
> ```
> *.[ab].example.com
> [ab].example.com
> *.example1.com
> *.example2.com
> ```
> 
> 可以来这里测试一下 http://www.globtester.com/

可以这样么?
@(atest|btest).example.com
我在globtester.com上是可以解析成
-  atest.example.com
-  btest.example.com

但是在config里面配置excludes的时候
\-  "@(atest|btest).example.com"就无法解析了。

**Comment by virusdefender** [comment]
大概看了下，go 的这个 glob 实现比较简单，没有 `@`符号，可以先多写几条吧。
