### ISSUE TITLE
多线程并发报错的问题

### ISSUE THREAD

**Issue by chenhaoruo** [chaitin/xray#30]
`fatal error: concurrent map iteration and map write

goroutine 23989 [running]:
runtime.throw(0xd01b83, 0x26)
        /usr/local/go/src/runtime/panic.go:617 +0x79 fp=0xc001a79d18 sp=0xc001a79ce8 pc=0x4308e9
runtime.mapiternext(0xc001a79e40)
        /usr/local/go/src/runtime/map.go:860 +0x59e fp=0xc001a79da0 sp=0xc001a79d18 pc=0x40f61e
assassin/http.(*Request).clone(0xc0015b52c0, 0xc001f12001, 0xc001a79f40)
        /builds/lohengrin/assassin/http/request.go:446 +0x212 fp=0xc001a79f10 sp=0xc001a79da0 pc=0x9f9812
assassin/http.(*Flow).DeepClone(0xc00117fda0, 0xc000ef2090, 0x29e8d60800)
        /builds/lohengrin/assassin/http/resource.go:29 +0x3a fp=0xc001a79f38 sp=0xc001a79f10 pc=0x9fdfca
assassin/controller.(*unit).run.func1(0xc001118690, 0xe11540, 0xc000fe0c00, 0xe11480, 0xc00117fda0)
        /builds/lohengrin/assassin/controller/controller.go:40 +0xd4 fp=0xc001a79fb8 sp=0xc001a79f38 pc=0xaef514
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc001a79fc0 sp=0xc001a79fb8 pc=0x45de71
created by assassin/controller.(*unit).run
        /builds/lohengrin/assassin/controller/controller.go:36 +0x13f`

win64下在使用多线程的时候报错

**Comment by phith0n** [comment]
求个复现的步骤吧，你是怎样触发这个问题的，求一下步骤，然后能不能稳定触发？

**Comment by chenhaoruo** [comment]
就是正常启动监听：` .\xray_windows_amd64.exe webscan --listen 127.0.0.1:7777 --text-output res.txt`
其他就是正常访问，应该是在被动扫描爆破登录口的时候多线程报错的，已经崩了好几次了

**Comment by zema1** [comment]
今天解决 (先立下 flag

**Comment by chenhaoruo** [comment]
哈哈，师傅辛苦~

**Comment by zema1** [comment]
sorry, 拖了一下，因为发现了几个相关的问题想一并解决了，新的版本应该安全了，如果问题可以再新开 issue。
