### ISSUE TITLE
输出 json 数据

### ISSUE THREAD

**Issue by monstersb** [chaitin/xray#34]
输出结果时能不能不依赖文件，直接在 stdout 里输出 json 格式的结果

**Comment by virusdefender** [comment]
以前是这样的，但是输出会很长很乱。

**Comment by phith0n** [comment]
其实理论上`-`表示标准输出，所以`--json-output -`应该是可以输出到stdout里的。

**Comment by phith0n** [comment]
最好的应该这样，所有log打印的部分输出在stderr里，包括debug、info等级的信息，stdout默认没有内容，如果指定了`--xx-output -`则输出在stdout，否则输出在具体文件里。而默认情况下（什么也没指定时），`--text-output -`默认加上。

这样有几个好处，首先如果要管道传递输出的话，不会把log的信息也传递过去；其次漏洞一律输出到文件里，是统一的，而stdout也是个文件，这个也是统一的；最后在默认情况下用户看到的和我们现在输出的内容是一致的。

**Comment by virusdefender** [comment]
有道理，现在 stdout 输出的日志或者漏洞其实都是为了方便直观看的，日志和漏洞其实还是建议写到文件中的，这样 stdout 就可以直接忽略。

**Comment by virusdefender** [comment]
这个先 close 了，现在建议用 html-output 看
