### ISSUE TITLE
代理设置增强建议

### ISSUE THREAD

**Issue by tuian** [chaitin/xray#37]
- mitm走一条线路代理，或者强制不走代理，即使设置了`export http_proxy=*`
- scan流量走另外一条代理，比如`export http_proxy`中定义的。过waf，防止被封等需求。

配置文件配置，或者命令参数，来区分。

**Comment by virusdefender** [comment]
确实 mitm 不应该受到太多的限制，现在配置文件中的 http 配置响控制所有的 http 请求。

同时 https://github.com/chaitin/xray/issues/36 的`0x01 headers问题`可以合并考虑下

**Comment by virusdefender** [comment]
应该改了，删除配置文件重新生成下 

文档参考 https://chaitin.github.io/xray/#/guide/proxy

有问题可以随时回复
