### ISSUE TITLE
动态扫描规则建议

### ISSUE THREAD

**Issue by tuian** [chaitin/xray#38]
比如，清洗好的流量，走`mitm`给`xray`喂数据时，可以动态控制扫描规则`sqli,xxe,ssrf`.

比如可以在headers，cookie，url参数上附加，进行动态规则控制.

```c
//mitm添加headers
Scan_Type: ssrf,sqli,lfi 
//Cookies上
Scan_Type=ssrf,sqli,lfi;
```

最终实现，看到参数中有`url`，就仅测试`ssrf`。判断参数中有"Sort=desc", 就仅测试`sqli`

另外，遇到这些附加的头，接收后，一定要删掉！

**Comment by virusdefender** [comment]
这个倒是挺像数据库优化 hint 的

```
SELECT /*+ NO_SEMIJOIN(@subq1 FIRSTMATCH, LOOSESCAN) */ * FROM t2
  WHERE t2.a IN (SELECT /*+ QB_NAME(subq1) */ a FROM t3);
```
