### ISSUE TITLE
建议加一个请求延时的功能

### ISSUE THREAD

**Issue by yhisme** [chaitin/xray#388]
请求网站过频繁的话很可能被banIP，如果像burp的扫描那种可以加一个每个请求都能自定义一个延时才请求就好了。

**Comment by zema1** [comment]
所以目前 `max_qps` 基本可以满足？
没法像 burp 那样为每个请求定义延时，因为不是 GUI

**Comment by virusdefender** [comment]
先用 max_qps 吧，有任何问题可以继续回复
