### ISSUE TITLE
xray单线程或多线程循环使用会出现错误

### ISSUE THREAD

**Issue by strengthen8** [chaitin/xray#393]
一个扫描器正常来说应该支持批量扫描公司的资产把,发现两次以上调用会出现xray.db错误的情况，麻烦处理下哈

**Comment by virusdefender** [comment]
你是每次启动一个新进程，然后 `--url` 使用的？这样也太慢了，正确的方式是代理或者爬虫模式，`--url` 只是为了方便一些特别简单的场景下测试用的。

`db_file_path` 只能一个进程打开，如果实在想多个进程的话，可以在配置文件中设置不同的 `db_file_path` 的路径。
