### ISSUE TITLE
建议增加类似sqlmap的针对单个url的--data的post扫描

### ISSUE THREAD

**Issue by notwhy** [chaitin/xray#4]
我的想法是这样的哈。我这边有一堆爬好的url链接存在数据库 有method url data字段 想用这个批量测试。

**Comment by monstersb** [comment]
个人感觉更合理的方式是使用代理的方式启动 xray，然后把这些数据批量打到 xray 的代理端口上

**Comment by notwhy** [comment]
**把这些数据批量打到 xray 的代理端口**
不太理解这句话的含义
意思是我本地构造好相关http请求 然后通过某个途径 （新功能）发送给xray的代理端口 使其识别并检测吗？ 是不是可以理解为可以把完整的http请求（类似于被动检测）交给代理端口来处理。 
如果是这样的话都ok的。

**Comment by zema1** [comment]
感觉可以支持下，我们自己 debug 也会方便点。

**Comment by zema1** [comment]
https://github.com/chaitin/xray/releases/tag/v0.3.0 已支持，如有问题可以继续回复。
