### ISSUE TITLE
Host绑定建议

### ISSUE THREAD

**Issue by tuian** [chaitin/xray#40]
类似以下的效果
```c
 curl --resolve ip.cn:443:1.1.1.1  https://ip.cn -H 'Host: ip.cn' -v --connect-timeout 5
```

走mitm时，`ssl/sni hostname`，是`ip.cn`, 强制绑定到`1.1.1.1`.
比如内网测试环境绑`host`的场景, 也有跨国分运营商走`edns`智能解析的场景。
也比如找到了源站`ip`, 就可以绕`waf`了。

**Comment by zema1** [comment]
需求比较小众，咱不考虑了

**Comment by zema1** [comment]
https://github.com/chaitin/xray/issues/771
