### ISSUE TITLE
希望白名单扫描域中增加区分端口号

### ISSUE THREAD

**Issue by gdbingo** [chaitin/xray#42]
配置文件config.yaml中，设置允许扫描的域的时候，发现如果设置域的时候是带端口号的话（例如这种：- "10.17.65.135:1289/*"），以代理模式开启xray后，挂了一下午没什么反应。希望白名单扫描域中增加带端口号的识别，满足测试带端口号的URL的需求

**Comment by Jarcis-cy** [comment]
已实现
