### ISSUE TITLE
批量扫描

### ISSUE THREAD

**Issue by notwhy** [chaitin/xray#423]
比如 --basic-crawler  只能指定一个url
./xray_darwin_amd64 --log_level=debug  webscan --basic-crawler http://ip
希望 添加一个-f选项 可以批量添加url 类似与可以进行批量扫描的这种

**Comment by lxl315** [comment]
同求

**Comment by notwhy** [comment]
xray监听端口,数据包封装成代理的格式，发送给代理端口，可以实现批量扫描。
如下:
`proxies = {
    "http": "http://user:pass@127.0.0.1:9000"
}
for _ in url
    r = requests.get(_, proxies=proxies)
`
