### ISSUE TITLE
建议 MITM 增加扫描状态获取 API

### ISSUE THREAD

**Issue by imp0wd3r** [chaitin/xray#443]
MITM 模式下如果想要判断扫描是否完成，需要在浏览器端测试结束后再观察 xray 的 log，能否提供一个 API 接口来获取扫描状态，这样可以方便自动化判断。

**Comment by virusdefender** [comment]
你是说想知道有没有 pending 的请求么？

**Comment by imp0wd3r** [comment]
是的，如果有接口的话可以在浏览器测试完毕后开始轮询，获取到没有 pending 的请求后发送通知，这样自动化方便一点。

**Comment by zema1** [comment]
这个如果要加可能也做成 webhook 那种，起一个 server 跟现有的设计不太契合，而且有了 server 就会有人想通过 api 创建任务、查询漏洞等。
所以还是想做的简单点，这个功能(webhook方式)等我整理下文档再加

**Comment by virusdefender** [comment]
https://chaitin.github.io/xray/#/api/statistic

可以试试看，有任何问题可以继续回复
