### ISSUE TITLE
新版本反连一直失败

### ISSUE THREAD

**Issue by timwhitez** [chaitin/xray#464]
更新最新版xray后反连到反连平台就一直失败
Remote server test failed, error invalid response from remote reverse server, response is: {"code":2,"data":"Login Required"}
反连平台是搭在linux x64 vps上，可以访问web页面。

**Comment by virusdefender** [comment]
看了下，是因为 `health_check` 的 api 加了 token 验证，但是调用方没加 token 导致的，但是实际使用应该没问题。

下个版本修一下

**Comment by virusdefender** [comment]
应该修了
