### ISSUE TITLE
针对.net+mysql的宽字节注入扫描会出现误报情况

### ISSUE THREAD

**Issue by leiyuch** [chaitin/xray#482]
![81571212383_ pic](https://user-images.githubusercontent.com/1195803/66899153-14858500-f02d-11e9-88b5-fde6fd83ee50.jpg)

如图

**Comment by zema1** [comment]
麻烦补充点详细的信息？ 报告上有提交误报的功能，或者群里私聊我吧  我是 `Koalr`

**Comment by leiyuch** [comment]
已解决
