### ISSUE TITLE
--url-file选项的时候，如果url访问失败，xray就会退出，不会扫描整个文件

### ISSUE THREAD

**Issue by JKme** [chaitin/xray#496]
在使用--url-file的时候，如果是访问失败，xray就不会扫描之后文件里面的链接，比如在扫描的最上面的url是http://xxxxxxxxxxxaaaaa.com:

[DBUG] 2019-10-23 14:01:24 +0800 [default:client.go:227] GET http://xxxxxxxxxxxaaaaa.com
[ERRO] 2019-10-23 14:01:25 +0800 [collector:url-list.go:42] Get http://xxxxxxxxxxxaaaaa.com: read tcp 198.18.0.1:49388->198.18.14.115:80: read: connection reset by peer
[INFO] 2019-10-23 14:01:25 +0800 [default:single.go:241] wait for task done

程序就会退出，建议忽略或者打印到日志继续扫描。

**Comment by zema1** [comment]
感谢反馈，今天会发版修复

**Comment by JKme** [comment]
> 感谢反馈，今天会发版修复

另外是否可以考虑如果url的格式是baidu.com，扫描器默认添加http:// ，对于http://baidu.com或者https://baidu.com 直接扫描，否则添加默认的http://

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by zema1** [comment]
> > 感谢反馈，今天会发版修复
> 
> 另外是否可以考虑如果url的格式是baidu.com，扫描器默认添加http:// ，对于[http://baidu.com或者https://baidu.com](http://baidu.com%E6%88%96%E8%80%85https://baidu.com) 直接扫描，否则添加默认的http://

今天的版本你说的这两个应该都处理 可以试下https://github.com/chaitin/xray/releases/tag/0.14.3
