### ISSUE TITLE
支持request文件

### ISSUE THREAD

**Issue by neal1991** [chaitin/xray#5]
像sqlmap中可以直接使用请求的 request 文件

**Comment by zema1** [comment]
问题不大，新版将支持，敬请期待。

**Comment by zema1** [comment]
https://github.com/chaitin/xray/releases/tag/v0.3.0 已支持，如有问题可以继续回复。

**Comment by neal1991** [comment]
该如何使用啊，我看文档也没有说明啊，--help 信息也没有提到，可以说明一下么，谢谢！ @zema1

**Comment by virusdefender** [comment]
`./xray webscan --help` 中的 `--raw_request FILE  load http raw request from a FILE`
