### ISSUE TITLE
试用了windos版和linux版，都出现了如下错误

### ISSUE THREAD

**Issue by dd404x** [chaitin/xray#520]
![image](https://user-images.githubusercontent.com/19923974/67735163-455ab680-fa3e-11e9-8c4a-436c5371f842.png)

**Comment by virusdefender** [comment]
这个是正常的，上面的 eof 信息应该是某个历史版本的 bug，你可以更新到最新看下。

另外如果是未授权扫描 `*gov.cn` 很危险的

**Comment by virusdefender** [comment]
先 close 了，有问题可以继续回复。
