### ISSUE TITLE
漏洞结果的webhook的信息太少，不方便集成到其他扫描系统

### ISSUE THREAD

**Issue by 40huo** [chaitin/xray#522]
在集成其他自动化扫描系统的时候，任务调度时会需要更多信息。

比如，希望能在起任务的时候传一个taskid，在扫描结束后能在webhook内把taskid返回给自动化系统，方便后续的处理。

如果能在起任务的时候添加一个 meta 字段，结果返回时自动把 meta 全部带上返回，这样就能解决问题。

另外，有没有计划起一个接口用来远程添加任务？命令行的方式不太好管理。

**Comment by virusdefender** [comment]
这个其实就是商业版在做的事情

> 商业版=xray+更多插件和模块+调度+前后端

所以这个事情在 xray 里面来做暂时不太可能，得自己去做了。

**Comment by 40huo** [comment]
好的，了解了
