### ISSUE TITLE
目录扫描优化建议（如 Index of）

### ISSUE THREAD

**Issue by notwhy** [chaitin/xray#528]
现在的问题是如果有index of
xray 开启dirscan 会报一堆dirscan的漏洞
建议:目录扫描如果有Index of等，就不在进行一些目录扫描等。

**Comment by virusdefender** [comment]
没懂，目录扫描如果有Index of等，就不在进行一些目录扫描等是什么意思啊，列目录就是 dirscan 要做的事情之一。

**Comment by notwhy** [comment]
暂时关闭，可能是我操作的问题
