### ISSUE TITLE
建议可以增加在线更新及更新后读取原来的config文件

### ISSUE THREAD

**Issue by harris2015** [chaitin/xray#568]
1. 在线更新或增加命令 --update更新
2. 由于更新后会自动生成新的config文件 但新的config文件不会读取旧版config文件里面修改的值 所以建议在生成config文件之前有个读取旧版config值的操作 然后生成新的config文件后 直接写入
避免了手动复制替换操作。

**Comment by zema1** [comment]
--update 那个比较简单

配置文件的处理上可能没那么简单，配置文件的格式可能变的，暂时不打算兼容多个版本的配置，不兼容时就会报错。

如果有旧的配置文件，不会新生成，只有在目录下没有配置文件才会重新生成，如果没有报错，原来的配置文件是可以正常使用的

**Comment by harris2015** [comment]
但是新版本的插件不会加载。。。

**Comment by zema1** [comment]
https://github.com/chaitin/xray/releases/tag/0.17.0 后可以自动更新了
至于配置文件那个问题，由于设计的问题，感觉暂时不会改了。
