### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by noraj** [chaitin/xray#586]
Is that possible to translate the README and the documentation in English too?

**Comment by virusdefender** [comment]
README translation https://chaitin.github.io/xray/#/en-us/generic/README

translation of other documents may need some time

if you have some specific questions, feel free to open issue

**Comment by noraj** [comment]
I was asked to add your tool to the Rawsec Cybersecurity Inventory: https://inventory.rawsec.ml/

So I wanted to check what the tool was about before adding it. Also I don't feel to add tools without a proper documentation in english so that anyone can understand, until now I didn't add language specific stuff. Also the tools seems to have a lot of features and I'm curious to discover it.

I'm waiting for an English doc :wink:

**Comment by zema1** [comment]
We need some volunteers to do the translation.  😷
