### ISSUE TITLE
建议SQL注入等其他插件可以自定义检测payload

### ISSUE THREAD

**Issue by ffpepwowa** [chaitin/xray#60]
建议添加一个sql注入的配置文件，里面可以使用自定义payload，因为每一个人对SQL语句认识不同，有的人使用的payload可能比较特殊。
还有就是写死payload的话如果目标存在SQL注入，但是存在waf，像这样传统的'and ''='或 and 1=1这种方式是没办法发现的。这时候需要自定义payload更为有效去发现SQL注入。

**Comment by zema1** [comment]
暂时可能不太好做，搁置一下

**Comment by stayliv3** [comment]
感觉这个还是有需求，可以自定义一个payload，然后用框架在每个参数和输入点进行扫描，检查结果。

**Comment by Jarcis-cy** [comment]
我们会在将来要出的xray 2.0系列工具中的xscan中考虑这个问题，感谢您的反馈
