### ISSUE TITLE
没有漏洞产生建议不生成html文件

### ISSUE THREAD

**Issue by notwhy** [chaitin/xray#604]
用supervisor启动xray 防止挂掉
command=/root/xray_linux_amd64 --log_level=info webscan --plugins sqldet,cmd_injection,dirscan,path_traversal,xxe,phantasm,upload,brute_force,jsonp,ssrf,baseline,redirect,crlf_injection,xss--listen 0.0.0.0:9000 --webhook-output http://127.0.0.1:5000/webhook --html-output xray__timestamp__.html
发现不管有没有漏洞 都生成了html文件 导致该文件过多 在没有漏洞的时候能不能不生成html文件
![image](https://user-images.githubusercontent.com/11815957/71341917-3c95e500-2596-11ea-90fc-4a27710009e5.png)

**Comment by virusdefender** [comment]
有道理，考虑和 html 可以追加放在一起做。

**Comment by zema1** [comment]
新版已支持该特性
