### ISSUE TITLE
运行之后就退出了，截图如下：

### ISSUE THREAD

**Issue by Saferman** [chaitin/xray#61]
![图片](https://user-images.githubusercontent.com/17509858/63107555-bea64980-bfb7-11e9-822b-822e6d7d36b5.png)

**Comment by Saferman** [comment]
使用的命令 xray_windows_amd64.exe webscan --url "http://*****某网址**/"

**Comment by virusdefender** [comment]
`--url` 只会扫描一个 url 

参考 https://chaitin.github.io/xray/#/generic/README?id=%f0%9f%9a%80-%e5%bf%ab%e9%80%9f%e4%bd%bf%e7%94%a8
