### ISSUE TITLE
【漏报】post form data请求数据未检测或者漏报

### ISSUE THREAD

**Issue by LeoHuang2015** [chaitin/xray#637]
Version: 0.17.2/08669353/COMMUNITY
地址：http://demo.aisec.cn/demo/aisec/      其中post_link.php?id=1&msg=1 以form-data形式post，未进行检测。
测试：通过爬虫或者wvs crawl的url已经喂取。

**Comment by virusdefender** [comment]
我试了下，sql 是可以检测的啊，xss 好像本来就不存在？

你的问题可能是

 - 请求失败了，可以看下日志
 - 请求被去重了，因为之前扫过，有可能没成功之类的？

先 close，有任何问题可以继续回复，感谢~
