### ISSUE TITLE
xray被动扫描时卡住

### ISSUE THREAD

**Issue by zerokeeper** [chaitin/xray#639]
`[ERRO] 2020-01-05 15:40:35 +0800 [cmdi:cmd_injection.go:77] context deadline exceeded
[ERRO] 2020-01-05 15:40:35 +0800 [cmdi:cmd_injection.go:77] context deadline exceeded
[ERRO] 2020-01-05 15:40:35 +0800 [cmdi:cmd_injection.go:77] context deadline exceeded
[WARN] 2020-01-05 15:40:39 +0800 [default:client.go:209] request to https://:2087/login/?login_only=1 failed, retrying (1 / 1)...
Statistic: targetScanned: 1066, requestSent: 352037, latency: 0.00ms, failedRatio: 2.97%
[ERRO] 2020-01-05 15:40:44 +0800 [sqldet:detector.go:57] Get https://:2087/login/?login_only=1: dial tcp 103.26.142.136:2087: i/o timeout

[ERRO] 2020-01-05 15:40:44 +0800 [sqldet:detector.go:84] Sample number 0/3 is not enough
Statistic: targetScanned: 1069, requestSent: 352057, latency: 234.73ms, failedRatio: 2.97%`

xray被动扫描时卡住，估计是waf拦截了请求，导致后面其它url的被动扫描也无法进行，希望处理一下，跳过当前的url，不然整个扫描任务一直阻塞着

**Comment by zema1** [comment]
实际上不是卡住，内部有个超时时间，超过 3 分钟就会跳过处理，这个逻辑可以再细化一些

**Comment by zerokeeper** [comment]
但是时间等待时间远不止，等了一两个小时候后，还是卡在那里，每次我就只有强行结束退出，任务量大的时候都出现了

**Comment by zema1** [comment]
新版做了一些处理 应该会改善这种情况的速度，卡住的表现为请求数长时间不再增长（3分钟），如果仍在增长就不是卡住。如有问题可以再开 issue 讨论

**Comment by dongfangyuxiao** [comment]
使用最新版的偶尔也会出现Sample number 0/3 is not enough，大概就会有几个包返回502

**Comment by virusdefender** [comment]
@dongfangyuxiao 

你这问题就是后端服务器返回的 502，和 xray 无关，可以尝试降低 `max_qps` 来缓解后端压力。

`Sample number 0/3 is not enough` 是 sql 注入插件提示的，它需要预先收集一些信息，否则无法继续检测。有疑问可以用 burp 作为 xray 的代理来确认下。
