### ISSUE TITLE
windows下的xray体验

### ISSUE THREAD

**Issue by caoxiangyu666** [chaitin/xray#640]
为了方便使用设置了环境变量，但是默认的文件输出目录发现都是当前cmd的目录，不知道能不能在配置文件里配置默认的例如config.yaml html报告 ca证书的输出目录。

**Comment by virusdefender** [comment]
没懂，你环境变量配置了啥，如果是根目录也可用于路径上啊

```
./xray --html-output $somepath/somepath/1.html
```

**Comment by caoxiangyu666** [comment]
这样不是每次都需要配置嘛，如果可以在配置文件中指定默认输出目录感觉比较好。

**Comment by virusdefender** [comment]
那你配置文件不也得每次重新生成么，和在命令行上有啥区别。
