### ISSUE TITLE
[需求讨论] 希望增加一个录制请求 + 重放请求扫描功能

### ISSUE THREAD

**Issue by VillanCh** [chaitin/xray#648]
场景:
    某一个域名下的 web 应用需要反复进行测试(非登录状态), 每次测试的时候, 都需要重新挂代理点点点, 但是实际上, 每次挂代理点点点的流量都是基本相同的, 希望能保存一份这样的流量. 具体在巡检的时候, 就可以选择多次测试; 具体测试频率可能是每天几次, 几天一次不等...

问题:
   重复的开启代理点点点耗费人力物力

预期解决办法:

通过类似命令 `xray collecting-requests --port 4444 --output requests_{{website_domain}}_{{date}}.xray.tar.gz` 收集请求

通过 `xray reply-requests --file requests_xxxcompany_2020_1_23_14_12.xray.tar.gz` 来执行扫描任务, 扫描结束就结束

**Comment by VillanCh** [comment]
类似需求: https://github.com/chaitin/xray/issues/647

**Comment by virusdefender** [comment]
一种简单的方法是使用 burp proxy 记录流量，然后保存为 xml 然后通过代理重放

**Comment by VillanCh** [comment]
这个方案是已经了解的, 主要是希望自动化这一个步骤, 流量来源可能是测试部门的流量这种, 自动化的价值可能更大一些

**Comment by SwagXz** [comment]
和burp联动重放不可以吗

**Comment by Jarcis-cy** [comment]
这个场景听起来联动rad应该就可以解决了

**Comment by Jarcis-cy** [comment]
不过确实存在爬虫记录不到的流量,后续或许可以通过自定义插件的形式尝试实现这个需求

**Comment by Jarcis-cy** [comment]
商业版有这个功能，可能会在将来要发的xscan中实现
