### ISSUE TITLE
windows版本一启动就卡死

### ISSUE THREAD

**Issue by ChristopherKai** [chaitin/xray#662]
![image](https://user-images.githubusercontent.com/3326425/72498342-06344880-386a-11ea-8b69-acc5adafd787.png)

**Comment by virusdefender** [comment]
完整的 cmd 截图和命令给一下吧

**Comment by ChristopherKai** [comment]
命令：`xray_windows_amd64.exe webscan --listen 127.0.0.1:8888 --html-output out.html`

**Comment by zema1** [comment]
你可能进入了交互式终端 没有退出。 https://xray.cool/xray/#/configration/cli?id=%e4%ba%a4%e4%ba%92%e5%bc%8f%e5%91%bd%e4%bb%a4%e8%a1%8c

另外 建议 windows 下使用 powershell

**Comment by ChristopherKai** [comment]
我使用powershell也是一样的情况，直接进入xray的交互式终端，没有任何提示，直接卡死。

**Comment by virusdefender** [comment]
xray 在  Windows 下面的交互式终端应该好久之前就去掉了，麻烦看下你的版本？
