### ISSUE TITLE
xray反连平台怎么删除记录？

### ISSUE THREAD

**Issue by leveryd** [chaitin/xray#667]
重复的记录太多了，想要删掉。

有对应的api、或者怎么操作db文件删除？

我尝试sqlite3 xray.db，直接操作数据库，但是好像数据库是加密了？

**Comment by virusdefender** [comment]
那不是 sqlite 数据库，目前界面上没删除功能，可以通过重命名 xray.db 来重新生成数据库实现删掉。

相关的功能将继续优化，感谢反馈，有任何问题可以继续回复。
