### ISSUE TITLE
联动扫描出现扫描卡住的情况

### ISSUE THREAD

**Issue by zZiFeiyu** [chaitin/xray#671]
联动扫描卡住的情况 群里好多人都遇到了 不知道是队列问题还是怎么 
队列里有url 但就是 不继续扫描  网络连接也没问题

**Comment by virusdefender** [comment]
首先你得看下界面上输出的 pending 和扫描的 url 数量有没有变

**Comment by zZiFeiyu** [comment]
url数量没有变化




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LiYang"<notifications@github.com&gt;; 
发送时间: 2020年2月15日(星期六) 晚上6:21
收件人: "chaitin/xray"<xray@noreply.github.com&gt;; 
抄送: "五行缺钱"<51055239@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [chaitin/xray] 联动扫描出现扫描卡住的情况 (#671)




首先你得看下界面上输出的 pending 和扫描的 url 数量有没有变

**Comment by zema1** [comment]
目前来说 基本不太可能在扫描时卡住，如果有 pending 的 url 同时请求数长时间没有增长才可能卡住。如果遇到这种情况，请不要退出，麻烦联系群里管理员看下。如果不是新版，请用最新版。

**Comment by zema1** [comment]
没有后续回复了 如果还有问题可以再讨论

**Comment by zZiFeiyu** [comment]
出现的就是 pending 的 url 同时请求数长时间没有增长   一直会停在提示
