### ISSUE TITLE
需求:增加ICMP和TCP记录

### ISSUE THREAD

**Issue by djerryz** [chaitin/xray#675]
DNS解析记录不会看到解析记录的情况:
1. 目标主机要是没有配置DNS server
2. 或者防火墙禁止UDP协议

所以希望能在revere的页面上增加一个端口监听的功能, 比如监听IP_A:9999(nc -lvvp 9999), 那么在手工测试的时候, IP_A:9999可以作为payload的一部分, (tcpdump)只要看到有SYN连接到9999端口, 则记录IP并展示到页面上.

还有一个问题就是防火墙禁止了外向的TCP协议,仅允许白名单IP的情况, 那么上述TCP也记录也无法获取到记录.
因此希望在页面上增加一个ICMP的记录功能, 比如设定了ICMP的data长度为221, 那么
ping IP_A -s 221, 则进行记录.

**Comment by zema1** [comment]
你说的有道理，但可能短期内加不上，xray 中的反连平台大都是服务于一些情况下的而诞生的，ICMP 和 TCP 更偏向于独立的手工测试，很难在自动化测试中应用。
我感觉这些功能可以自己写个小的脚本实现，随用随起。

**Comment by Jarcis-cy** [comment]
反连的客户端在xray 2.0中将会变成一个插件，理论上可以接自己想要的服务
