### ISSUE TITLE
代理模式下统计API的请求规律

### ISSUE THREAD

**Issue by night-watchman** [chaitin/xray#691]
代理模式下统计API的请求规律，是怎样的？
会在扫描中持续的反馈统计信息吗，目前在我的使用中似乎是在扫描一段时间后统计信息便不再反馈了。

**Comment by zema1** [comment]
首先答案是持续反馈的，但有一个逻辑是，如果上一次统计的 pending 结果为 0，这一次就不打印了，防止没有数据时满屏都是 pending: 0 这条信息。

我用下来发现这样做也不太合适，后面会稍调整下，使其看起来是持续的反馈的。

**Comment by night-watchman** [comment]
pending指的是什么，是新增的请求吗

**Comment by zema1** [comment]
pending 是指队列中的请求数目，就是等待扫描的数目。新版优化了一下这个问题，可以试下。
