### ISSUE TITLE
Option to pass multiple target for webscan

### ISSUE THREAD

**Issue by gopinath6** [chaitin/xray#692]
Is there any option to pass multiple target through text file for webscan?

**Comment by zema1** [comment]
You can use `--url-file` argument:

```
$ cat 1.txt
http://example.com/
http://example.com/index.php?a=b

$ ./xray webscan --url-file 1.txt
```
It will test the two urls in `1.txt` without crawler. Testing multiple targets with crawler don't support now.

**Comment by gopinath6** [comment]
Ok.Thanks
