### ISSUE TITLE
Proxy Failed问题

### ISSUE THREAD

**Issue by admintony** [chaitin/xray#694]
将流量接入到xray以后，再访问站点就提示这个：
199 "martian" "proxyconnect tcp: dial tcp 127.0.0.1:8080: connect: connection refused" "Wed, 04 Mar 2020 16:01:21 GMT"

**Comment by admintony** [comment]
是个什么问题呢？

**Comment by virusdefender** [comment]
你配置了 mitm 的 upstream_proxy 了吧
