### ISSUE TITLE
是否可以添加dirscan的depth功能

### ISSUE THREAD

**Issue by rebirthwyw** [chaitin/xray#710]
如phantasm支持depth一样，在xray作为被动代理模式运行时，上级流量可能会传递过来a.com/1.html、a.com/2.html等等请求，但是对于dirscan功能来说，这些请求只需要对a.com进行目录扫描就可以了。因此，建议给dirscan添加一个类似phantasm的depth的功能，这样可以减少被动代理的很大一部分多余流量。

**Comment by zema1** [comment]
0.20.0 已支持
