### ISSUE TITLE
xss payload疑似错误

### ISSUE THREAD

**Issue by j4ckzh0u** [chaitin/xray#714]
测试链接: `http://xsst.sinaapp.com/xss/ext/6.php?libid=178&FilterAttrAND=3602&FilterValueAND=aa`
正确的payload为：`http://xsst.sinaapp.com/xss/ext/6.php?libid=178&FilterAttrAND=3602&FilterValueAND=aa%0a%20alert(1);//`

xray 提供的payload为：
```
Statistic: targetScanned: 552, requestSent: 87452, latency: 38.83ms, failedRatio: 0.00%
[Vuln: xss]
Target           "http://xsst.sinaapp.com/xss/ext/6.php?libid=178&FilterAttrAND=3602&FilterValueAND=aa%0a%20alert(1);//"
Payload          "\n;prompt(1);//"
Position         "query"
ParamKey         "FilterValueAND"
ParamValue       "dzgliswbnurmrsgurgmy"
```
经测试xray提供的payload并不能触发xss

![image](https://user-images.githubusercontent.com/38179297/77085018-b117dd00-6a3a-11ea-8ff1-9f774f5bc9bc.png)

**Comment by virusdefender** [comment]
这个 payload 没经过编码，而且为了能够正确的显示在 console 上，做了 repr 处理，否则会有一个空行。

![image](https://user-images.githubusercontent.com/4939404/77093885-9fd4cd80-6a46-11ea-80cb-c4e829b6ff67.png)

`\n` 编码之后就是你的 `%0d%0a`，所以没啥问题吧。

有任何问题可以继续回复。

**Comment by j4ckzh0u** [comment]
ok
