### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by qhxb** [chaitin/xray#728]
用代理模式进行扫描的时候，有特别多的 unexpected EOF，日志如下
Statistic: scanned: 7, pending: 0, capacity: 3000, requestSent: 1521, latency: 47.30ms, failedRatio: 14.53%
[ERRO] 2020-04-13 16:13:18 +0800 [collector-helper:httpmirror.go:37] unexpected EOF
[ERRO] 2020-04-13 16:13:20 +0800 [collector-helper:httpmirror.go:37] unexpected EOF
![image](https://user-images.githubusercontent.com/22363218/79106747-ac2e1b00-7da5-11ea-8d38-5abce1dc59fd.png)
抓包看了一下，好像如果请求类型是POST并且没有参数就会出现这个错误。还会自动在请求中加
头字段Warning: 199 "martian" "unexpected EOF" "Mon, 13 Apr 2020 16:43:47 GMT"
不知道会不会影响扫描
![image](https://user-images.githubusercontent.com/22363218/79107020-370f1580-7da6-11ea-9e89-818c3197dbeb.png)

**Comment by virusdefender** [comment]
能看下到代理之前的流量么，我猜测是 POST 的 `Content-Lenght` 不太对？

**Comment by qhxb** [comment]
看了一下，Content-Lenght确实对不上，数据包是从数据库拿的，存的时候应该就少了body。
在burp里测试没问题，burp会自动纠正。报“unexpected EOF”错还会继续扫描吗

**Comment by virusdefender** [comment]
不会，因为这样解析整个请求都会出错，自动修正可以，但是并不是一个科学的行为

**Comment by qhxb** [comment]
1

**Comment by LuanShiZhiJian** [comment]
Content-Lenght如何排查，有经验可以分享吗？谢谢！

**Comment by qhxb** [comment]
> Content-Lenght如何排查，有经验可以分享吗？谢谢！

xray可以设置代理，把xray流量代理到burp或者fiddler都能看到xay重组后的请求包

**Comment by qhxb** [comment]
> Content-Lenght如何排查，有经验可以分享吗？谢谢！

xay重组后的请求包：xray可以设置代理，把xray流量代理到burp或者fiddler都能看到xay重组后的请求包
xay重组前的请求包：我是从其他地方存在mongo里的，所以直接在mongo里看
