### ISSUE TITLE
connection reset by peer or broken pipe

### ISSUE THREAD

**Issue by 7x0** [chaitin/xray#734]
xray扫描的时候会遇到waf及封ip的情况，
想问问怎样可以实现通过代理ip去请求，如使用代理隧道

**Comment by virusdefender** [comment]
https://xray.cool/xray/#/configration/http?id=%e6%bc%8f%e6%b4%9e%e6%89%ab%e6%8f%8f%e7%94%a8%e7%9a%84%e4%bb%a3%e7%90%86-proxy
