### ISSUE TITLE
不支持json格式数据检测

### ISSUE THREAD

**Issue by CTF-MissFeng** [chaitin/xray#740]
有个json注入点手工检测存在，使用xray未检测出来，查看debug发现payload为以下这样：

`{"action":"GetInfoList","getTime":"2020-01-01","keyword":"aaa","id":"1","page":1,"dataSize":10} 'and/**/extractvalue(1,concat(char(126),md5(1973645267)))and'`

并未对json中每个参数值进行payload测试

**Comment by zema1** [comment]
是 `http://a.com/?a={"h":"e"}` 这种 json 吧，参数中的 json 暂不支持，考虑下个版本支持

**Comment by CTF-MissFeng** [comment]
> 是 `http://a.com/?a={"h":"e"}` 这种 json 吧，参数中的 json 暂不支持，考虑下个版本支持

不是这样的哦,感觉是解析json时问题：

1、如简单的json数据，可以正常：
![image](https://user-images.githubusercontent.com/38177965/79715224-b43a0d80-8305-11ea-941e-fa691b5436a2.png)

![image](https://user-images.githubusercontent.com/38177965/79715237-c6b44700-8305-11ea-95aa-f4e15be79a4d.png)

![image](https://user-images.githubusercontent.com/38177965/79715367-214da300-8306-11ea-9010-8755ba293b27.png)

2、这样json也很简单，但是它解析不了json数据

![image](https://user-images.githubusercontent.com/38177965/79715275-e8153300-8305-11ea-8db7-99fdcd743920.png)

![image](https://user-images.githubusercontent.com/38177965/79715327-1561e100-8306-11ea-810c-b1b7edf46e3a.png)

![image](https://user-images.githubusercontent.com/38177965/79715428-46daac80-8306-11ea-94d6-6d30f984881e.png)

**Comment by CTF-MissFeng** [comment]
> 是 `http://a.com/?a={"h":"e"}` 这种 json 吧，参数中的 json 暂不支持，考虑下个版本支持

找到原因了，原因是协议头中Content-Type值为json，xray才会当做json解析，如果Content-Type不为json,及时提交的数据为json也不解析

**Comment by virusdefender** [comment]
Content-Type 不对确实不好说直接的数据是啥格式的
