### ISSUE TITLE
需求讨论：给xray增加SQL注入检测程序

### ISSUE THREAD

**Issue by fumengze** [chaitin/xray#745]
xray检测到SQL注入后webhook到flask中，flask接收到url后，调用sqlmapapi进行自动注入检测，跑出数据库后把数据库信息发送至微信、钉钉、企业微信。

**Comment by virusdefender** [comment]
你是想表达什么

**Comment by fumengze** [comment]
xray社区有个活动，完善webhook的功能，在提交前要先发起讨论，看是否被否绝。我想用webhook，做一个对接sqlmapapi的程序，检测到SQL注入后自动获取数据库信息。

**Comment by virusdefender** [comment]
嗯嗯，了解，之前想错了。

这个感觉我们可以给一个 webhook 的基本插件框架然后去开发

**Comment by fumengze** [comment]
实际上webhook到sqlmapapi的脚本我已经写完了，使用flask，主要看这个需求接不接受。webhook的基本插件框架，这个想法挺不错的，我建议使用flask做成web服务，当xray扫描出相关漏洞时webhook到flask中，然后再调用相应的api或插件。

**Comment by wangsanshi123** [comment]
666

**Comment by virusdefender** [comment]
简单写了一个小的框架，方便上手开发

https://github.com/chaitin/xray/pull/746
