### ISSUE TITLE
webhook收不到xray的消息

### ISSUE THREAD

**Issue by iAmSOScArEd** [chaitin/xray#749]
如题
1、命令行截图如下，一开始我开启了webhook服务，但是发现收不到xray发来的数据，然后我就关掉了web服务，重新开启xray，按理讲127.0.0.1:5000没有启动的话是会报错的，但是却一直在这个界面。
![image](https://user-images.githubusercontent.com/34957454/81001008-a47c0680-8e79-11ea-9332-9793105990aa.png)
2、然后被动监听也不起作用，使用crawlergo，配置也正确，xray也收不到url
xray已升级至最新版，配置文件已重新生成。

**Comment by iAmSOScArEd** [comment]
附crawlergo命令 
crawlergo.exe -c F:/chrome-win/chrome.exe -t 5 -f smart --fuzz-path --output-mode json --push-to-proxy http://127.0.0.1:7777 --push-pool-max 10 http://xxx.com

**Comment by iAmSOScArEd** [comment]
使用 xray webscan --url "http://demo.aisec.cn/demo/aisec/js_link.php?id=2&msg=abc" --plugins xss --webhook-output http://127.0.0.1:5000/webhook 可以
使用xray webscan --listen 127.0.0.1:7777 --plugins xss --webhook-output http://127.0.0.1:5000/webhook 不行

**Comment by iAmSOScArEd** [comment]
好了，玄学般的又可以了。

**Comment by virusdefender** [comment]
你要是只接收漏洞消息，代理得有流量才行吧，看你的图，只是监听了代理，而没有请求去扫描。
