### ISSUE TITLE
Add SSL support to Cland

### ISSUE THREAD

**Issue by uBadRequest** [chaitin/xray#756]
Hello!
I really need to have ssl support for the XSS payload! I seeing errors where its blocking loading mixed content.

Also, when it takes over my domain, it would be nice to be able to create my own subdomains instead of the ones it generates automatically.

**Comment by uBadRequest** [comment]
I think we miss some vulnerabilities if the xss payload is not using https, and there doesn't seem to be the ability to generate a link using my domain name. Just IP and port?

**Comment by virusdefender** [comment]
a workaround method is you can use nginx as reverse proxy

**Comment by virusdefender** [comment]
> Also, when it takes over my domain, it would be nice to be able to create my own subdomains instead of the ones it generates automatically.

ok

**Comment by uBadRequest** [comment]
> a workaround method is you can use nginx as reverse proxy

Hey, I was thinking about that. How would I configure it to redirect all the payloads so that they get served over https? Payloads aren't executing :(

`Mixed Content: The page at 'examplesite.com' was loaded over HTTPS, but requested an insecure image 'http://133.13.13.13:39477/t/4927c5/SEzY/0/x.js'. This content should also be served over HTTPS.`

**Comment by virusdefender** [comment]
try to set `base_url` schema to https in config.yml, for example `https://133.13.13.13:39477/`

**Comment by uBadRequest** [comment]
> try to set `base_url` schema to https in config.yml, for example `https://133.13.13.13:${port}`

What would the nginx sites-available configuration look like? Can't seem to get this to work :(

**Comment by uBadRequest** [comment]
I got it by the way!

**Comment by virusdefender** [comment]
ok, feel free to submit issues~

**Comment by uBadRequest** [comment]
When I use nginx, how do you get cland to show the original IP?

![image](https://user-images.githubusercontent.com/47282747/84724737-844a6780-af4e-11ea-9998-6f7febe25184.png)

**Comment by virusdefender** [comment]
maybe it's a problem, a workaround is 

```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

then you can get the real ip from http headers, however, the `RemoteAddr` field is still wrong, i will add a config to reverse server later.

**Comment by uBadRequest** [comment]
If I wanted the base_url schema to be my domain name so that i dont have ssl errors, how would I configure the dns in the config file so that the root domain resolves?
