### ISSUE TITLE
对于Xray进程时常自行killed

### ISSUE THREAD

**Issue by Ryan0lb** [chaitin/xray#759]
![image](https://user-images.githubusercontent.com/15329046/82684397-18dde480-9c85-11ea-8a28-32b8f56e20c6.png)

**Comment by virusdefender** [comment]
可能是内存不够了，参考以下文档

 - https://xray.cool/xray/#/guide/faq?id=xray-%e5%9b%a0%e4%b8%ba-out-of-memory-%e8%80%8c%e5%b4%a9%e6%ba%83%e6%88%96%e8%a2%ab%e6%9d%80%e6%ad%bb  oom 的表现和排查
 - https://xray.cool/xray/#/guide/speed 为什么会 pending 这么多
