### ISSUE TITLE
dark-chain是什么洞，怎么利用

### ISSUE THREAD

**Issue by undefinedsec** [chaitin/xray#762]
如题，不知道dark-chain代表什么意思

**Comment by virusdefender** [comment]
报告上点下这是误报，然后回复给你啥原因

**Comment by sunlightcoder** [comment]
> 报告上点下这是误报，然后回复给你啥原因

已提交，麻烦看下。

**Comment by virusdefender** [comment]
看了下，应该是你的网站有一些 `display:none` 的链接，这个功能就是检查暗链（比如黑客给你插入了一些不可见的链接，用于搜索引擎爬虫访问，提高网站权重）。偏合规类插件，可以忽略下。
