### ISSUE TITLE
建议增加POST请求时对data数据的分块传输功能

### ISSUE THREAD

**Issue by CzGzBz** [chaitin/xray#77]
建议增加POST请求时对data数据的分块传输功能：
1、在config配置中可以设置POST请求时对data数据的分块传输功能开关。
2、在config配置中可以设置分块传输的分块长度或块数范围。
3、分块传输时分块长度后自动加上混淆字符串。

**Comment by virusdefender** [comment]
受限于标准库，暂时无法实现

https://github.com/golang/go/issues/33733

**Comment by Jarcis-cy** [comment]
当前似乎没有相关的漏洞需要这样的实现，如果需要，可能考虑使用go插件实现，感谢您的反馈！
