### ISSUE TITLE
当客户端设置hosts的时候，扫描对象出错

### ISSUE THREAD

**Issue by qhxb** [chaitin/xray#771]
业务场景：功能测试的时候设置hosts——使用代理抓包——保存数据包完整url部分包含真实的请求ip
问题：如图本来要测试10.10.10.10，但是测到www.baidu.com去了
![image](https://user-images.githubusercontent.com/22363218/84363930-feeb4e00-ac01-11ea-97a7-77fa312773f8.png)
这个能解决吗？（因为多客户端问题，不能在xray引擎服务器设置hosts）

**Comment by qhxb** [comment]
@zema1 我这个好像跟他有一点点区别，可能我描述的不是很准确。（概况就是：代理使用burp没问题，burp好像是直接通过四层包寻找目的ip端口。xray做代理的时候会修改7层数据包，根据7层数据包host字段寻找目的ip地址，就导致测试的时候有很多问题）
问题详情：https://www.cnblogs.com/xugongzi007/p/13150992.html
而且很多公司测试环境应该都会用到hosts。。。

**Comment by Jarcis-cy** [comment]
xray2.0已支持
