### ISSUE TITLE
开着被动扫描,访问了下公司的jira.被灌进去2000多条脏数据..

### ISSUE THREAD

**Issue by j14ncn** [chaitin/xray#772]
![image](https://user-images.githubusercontent.com/19720226/84573691-b3d56480-add4-11ea-9dee-35c536c23f96.png)

**Comment by kiang70** [comment]
优秀！说不定还能挖出个jira的洞呢:)

**Comment by virusdefender** [comment]
一个是配置好你浏览器的代理，不需要测试的站不要走代理，另外就是配置好 xray 的白名单，不需要测试的站不要扫描。见 https://xray.cool/xray/#/configration/mitm
