### ISSUE TITLE
Webscan UI

### ISSUE THREAD

**Issue by uBadRequest** [chaitin/xray#776]
Would it be possible to have a Webscan UI?
It appears there is a github repository that has this https://github.com/virink/xray-weblisten-ui

Could this be implemented into xray?

**Comment by virusdefender** [comment]
Maybe xray-weblisten-ui project is a bit rudimentary.

A web ui commonly contains two functions

 - task mangement
 - result management

### task management

In my opinion, it's too complex to translate the whole config to web ui, and most of them do not need to modify.

## result management

We have provided some frameworks to do this

You can use webhook to store result to database 

https://github.com/chaitin/xray/tree/master/webhook

and then load database result to html report

https://github.com/chaitin/xray/tree/master/report and https://github.com/chaitin/xray/issues/750
