### ISSUE TITLE
盲打平台支持第三方dns

### ISSUE THREAD

**Issue by notwhy** [chaitin/xray#780]
场景:外网有个dns平台 (zoomeye 或者其他)
mydns/api?token=&type=dns&filter=
优点：
我直接在配置里面贴URL进去 而不用xray新起一个dns

**Comment by virusdefender** [comment]
这个暂时不是太方便支持，xray 反连平台有些自己的需求，第三方平台不一定能满足需求，之后也许可以考虑来一个类似的云服务。
