### ISSUE TITLE
xray子域名收集

### ISSUE THREAD

**Issue by zglaozhu** [chaitin/xray#784]
xray子域名收集  可以读取文件，批量爆破查询么

**Comment by zema1** [comment]
xray 不支持这类批量操作。不过，这好像就是两行 shell 的事。

**Comment by zglaozhu** [comment]
请问大佬 shell  应该怎么写呢  win系统

**Comment by zglaozhu** [comment]
> xray 不支持这类批量操作。不过，这好像就是两行 shell 的事。

请问大佬 shell 应该怎么写呢 win系统
