### ISSUE TITLE
0.21.8 高级版 升级到 1.0.4 后 signature verification failed

### ISSUE THREAD

**Issue by hackzx** [chaitin/xray#786]
如题。
另外，跨平台版本license该如何获取？

thx

**Comment by phith0n** [comment]
找当时给你发license的同学问问？

**Comment by hackzx** [comment]
好的，感谢回复。

**Comment by virusdefender** [comment]
你的老版本可能是非官方版？

**Comment by virusdefender** [comment]
license 和平台无关

**Comment by hackzx** [comment]
> 你的老版本可能是非官方版？

Version: 0.21.8/92b968e0/UNIVERSE-ADVANCED
Licensed to XXX_专用高级授权, license is valid until 2666-06-06 06:06:06

**Comment by virusdefender** [comment]
你这就是破解版啊，万一再给你加个后门，挖的洞都是别人的了

**Comment by hackzx** [comment]
> 你这老版本是宇宙高级版啊，万一再给你加个后门，挖的洞都是别人的了

卧槽，被人忽悠了。
感谢答疑，清楚情况了。
