### ISSUE TITLE
可以提供一下xray自带的反连平台API吗

### ISSUE THREAD

**Issue by ck00004** [chaitin/xray#788]
可以提供一下xray自带的反连平台API吗，想在代码里面使用xray的反连平台

**Comment by virusdefender** [comment]
这个比较复杂，感觉可以提供一个 Python 的 demo，我稍后写下

**Comment by mekoko** [comment]
自己抓包写吧，加个x-token 头就行了

**Comment by 0d9y** [comment]
> 这个比较复杂，感觉可以提供一个 Python 的 demo，我稍后写下

这个目前有文档或者demo了么

**Comment by Jarcis-cy** [comment]
已经有了
