### ISSUE TITLE
怎么扫描只有微信接口的网站呢？

### ISSUE THREAD

**Issue by helintongh** [chaitin/xray#791]
使用xray扫描微信入口时request to https://open.weixin.qq.com/connect/objects/getImage.php?base64Url=YGVjaG8gcHlwbWFmaGggPiBsYWh3LnR4dGA%3D&format=png failed, retrying (1 / 1)...
会卡在登录界面上。

**Comment by zema1** [comment]
这类接口可能有限频之类的吧，暴力访问失败。可以先少开插件试试
