### ISSUE TITLE
介意扫描结果加一个分页，不然扫子域名时，数据太大，网页直接就崩溃了

### ISSUE THREAD

**Issue by Mimanchi666** [chaitin/xray#792]
介意扫描结果加一个分页，不然扫子域名时，数据太大，网页直接就崩溃了

**Comment by zema1** [comment]
分页可能解决不了这个问题。。 计划是分多分报告展示。

**Comment by zema1** [comment]
https://github.com/chaitin/xray/releases/tag/1.1.0 已解决
