### ISSUE TITLE
X-Frame-Options的值是大小写不敏感的，这里的正则也应该如此

### ISSUE THREAD

**Issue by neargle** [chaitin/xray#796]
误报如下
```json
{
    "expected_value": "^(deny)|(sameorigin)$",
    "header_name": "X-Frame-Options",
    "header_value": "SAMEORIGIN",
    "param": {},
    "port": 80,
}
```
参考 rfc7034 的标准里，X-Frame-Options 的 Header 值是不区分大小写的，且以设置大写居多： https://tools.ietf.org/html/rfc7034

> 2.2.   Augmented Backus-Naur Form (ABNF)
> 
>    The RFC 5234 [RFC5234] ABNF of the X-Frame-Options header field value
>    is the following:
> 
>          X-Frame-Options = "DENY"
>                    / "SAMEORIGIN"
>                    / ( "ALLOW-FROM" RWS SERIALIZED-ORIGIN )
> 
>          RWS             = 1*( SP / HTAB )
>                        ; required whitespace
> 
>    with serialized-origin as defined in [RFC6454] and required
>    whitespace (RWS) as defined in [HTTPbis-P1].
> 
>    RWS is used when at least one linear whitespace octet is required to
>    separate field tokens.  RWS SHOULD be generated as a single space
>    (SP).  Multiple RWS octets that occur within field-content SHOULD
>    either be replaced with a SP or transformed to all SP octets before
>    interpreting the field value or forwarding the message downstream.
> 
>    SP and horizontal tab (HTAB) are as defined in Appendix B.1 of RFC
>    5234 [RFC5234].
> 
>    **The values are specified as ABNF strings; therefore, they are case-
>    insensitive.**

**Comment by virusdefender** [comment]
感谢，稍后将调整下这个

**Comment by neargle** [comment]
师傅客气~

**Comment by zema1** [comment]
https://github.com/chaitin/xray/releases/tag/1.1.0 已解决
