### ISSUE TITLE
能不能加入新版本检测功能

### ISSUE THREAD

**Issue by monstersb** [chaitin/xray#8]
更新比较快，希望加上新版本检测功能，及时通知大家更新

**Comment by zema1** [comment]
嗯 近期会考虑添加该功能

**Comment by zema1** [comment]
https://github.com/chaitin/xray/releases/tag/0.4.0

**Comment by gsfish** [comment]
新版本检测是否可以通过参数/配置关闭呢，希望能有办法禁用以提高调用的效率

**Comment by Jarcis-cy** [comment]
> 新版本检测是否可以通过参数/配置关闭呢，希望能有办法禁用以提高调用的效率

师傅可以提一个新的issue，并详细描述一下需求
