### ISSUE TITLE
xray的pending队列满了之后，后续代理发送过来的请求会被丢弃吗

### ISSUE THREAD

**Issue by aboutbo** [chaitin/xray#800]

**Comment by zema1** [comment]
代理会阻塞住，直到漏洞扫描处理掉队列里的请求空出一个位置时就会继续工作。

**Comment by aboutbo** [comment]
> 代理会阻塞住，直到漏洞扫描处理掉队列里的请求空出一个位置时就会继续工作。

如果是联动awvs的场景下，队列满了之后，就会导致awvs的爬虫任务失败吧

**Comment by zema1** [comment]
> > 代理会阻塞住，直到漏洞扫描处理掉队列里的请求空出一个位置时就会继续工作。
> 
> 如果是联动awvs的场景下，队列满了之后，就会导致awvs的爬虫任务失败吧

应该是会的，在 awvs 层面看来 代理就是超时了
