### ISSUE TITLE
xray怎么配置目录字典?

### ISSUE THREAD

**Issue by zglaozhu** [chaitin/xray#802]
请问xray怎么配置目录字典呢 我win10配置绝对路劲
报错 did not find expected hexdecimal number, please backup and remove it and try again

**Comment by zema1** [comment]
配置缩进可能弄错了

**Comment by zglaozhu** [comment]
> 配置缩进可能弄错了

没有啊

**Comment by zema1** [comment]
刚试了下没问题，如果还有问题 请给出更多必要信息，比如贴出你的配置文件。
