### ISSUE TITLE
xray配合awvs12失败

### ISSUE THREAD

**Issue by fejl504** [chaitin/xray#810]
按照官方教程的进行awvs和xray联动扫描xray一直卡在这个地方

Enabled plugins: [sqldet cmd_injection dirscan path_traversal xxe phantasm upload brute_force jsonp ssrf baseline redirect crlf_injection xss darkchain]

[WARN] 2020-07-28 16:23:54 [reverse:http_server.go:515] reverse server configured to 127.0.0.1, which might fail to check the vulns that need reverse server
[WARN] 2020-07-28 16:23:54 [reverse:http_server.go:516] please modify the configuration according to https://docs.xray.cool/#/configration/reverse
[INFO] 2020-07-28 16:23:54 [reverse:http_server.go:186] starting reverse http server
[INFO] 2020-07-28 16:23:54 [default:webscan.go:456] reverse http server, listen: 127.0.0.1, base url: http://127.0.0.1:2917, token: sev1g8
[INFO] 2020-07-28 16:23:54 [default:single.go:76] set plugins parallel to 30
[INFO] 2020-07-28 16:23:54 [collector:mitm.go:226] loading cert from ./ca.crt
[INFO] 2020-07-28 16:23:54 [collector:mitm.go:227] loading cert key from ./ca.key
[INFO] 2020-07-28 16:23:56 [collector:mitm.go:264] starting mitm server at 0.0.0.0:1111

**Comment by zema1** [comment]
参考 https://docs.xray.cool/#/guide/faq?id=%e5%a6%82%e4%bd%95%e7%a1%ae%e8%ae%a4%e4%bb%a3%e7%90%86%e6%a8%a1%e5%bc%8f%e4%b8%8b-xray-%e6%9c%89%e6%b2%a1%e6%9c%89%e5%9c%a8%e5%b7%a5%e4%bd%9c
