### ISSUE TITLE
xray添加字典路劲错误

### ISSUE THREAD

**Issue by zglaozhu** [chaitin/xray#818]
xray爆破添加自己的字典会出现错误
系统win10
![image](https://user-images.githubusercontent.com/31888299/89289258-7fba4980-d689-11ea-9e69-284ceb220fc5.png)
![image](https://user-images.githubusercontent.com/31888299/89289292-92348300-d689-11ea-82cf-0edecf596d5f.png)

**Comment by zema1** [comment]
看 32 行, 报错信息说了

**Comment by zglaozhu** [comment]
> 看 32 行, 报错信息说了

不明白报错信息，应该怎么修改呢

**Comment by zema1** [comment]
稍微看了下，windows 下的路径写法和 linux 的不太一样，因为 windows 下的路径分隔符 `\` 本身是个转义字符，需要这样写：

原来:
```
C:\Users\test\1.txt
```
写成
```
C:\\Users\\test\\1.txt
```

即变成 `\\`

**Comment by zglaozhu** [comment]
> 稍微看了下，windows 下的路径写法和 linux 的不太一样，因为 windows 下的路径分隔符 `\` 本身是个转义字符，需要这样写：
> 
> 原来:
> 
> ```
> C:\Users\test\1.txt
> ```
> 
> 写成
> 
> ```
> C:\\Users\\test\\1.txt
> ```
> 
> 即变成 `\\`

谢谢 已经ok
