### ISSUE TITLE
扫描时候能忽视自定义的url_keywords吗

### ISSUE THREAD

**Issue by Swmped** [chaitin/xray#821]
比如能添加带cookie扫描的时候排除注销，修改密码等链接的参数吗

**Comment by pupiles** [comment]
mitm:
  ca_cert: ./ca.crt
  ca_key: ./ca.key
  auth:
    username: ""
    password: ""
  restriction:
    includes: # 允许扫描的域，此处无协议
    - '*' # 表示允许所有的域名和 path
    - 'example.com' # 表示允许 example.com 下的所有 path
    - "example.com/admin*" # 表示允许 example.com 下的 /admin 开头的 path
    excludes:
    - '*/logout.php'
    - '/*logout*'

同问，这个配置设置了理论上忽略掉在任意域名下包含"logout"的路由但被动扫描的时候xray还是会访问logout的页面,url由crawlergo提供，crawlergo配置了--ignore-url-keywords logout

**Comment by zema1** [comment]
代理本身是不受这个限制的，这个配置项目前的含义是进行漏洞扫描。就是说挂着代理点相关链接还能访问 但是不会进行漏洞扫描。目前设计就是这样的。
