### ISSUE TITLE
与awvs12联动扫出来的误报信息

### ISSUE THREAD

**Issue by ll-lingling** [chaitin/xray#828]
在做漏扫的时候，两家不同的政府部门，不同的域名，扫出来的漏洞信息相同
![image](https://user-images.githubusercontent.com/49424291/90003378-9171a180-dcc6-11ea-9779-6c58867bc6a7.png)
![image](https://user-images.githubusercontent.com/49424291/90003426-a9492580-dcc6-11ea-993e-a96e2a6f18b0.png)

**Comment by ll-lingling** [comment]
两张图分别是两家公司，两个域名扫描得出的

**Comment by zema1** [comment]
感觉整体表述不太清楚，没明白要表达什么，比如

1. 为何两张图的域名一样，但你说是两个域名的，是不是 awvs 联动的配置有问题呢
2. 为何说是误报，从已有的信息我没法判断出任何误报信息，是说图里的都是误报吗，如果这样的话，请点击报告中的反馈误报，我会看到。

**Comment by to9929** [comment]
确实误报很多一样
