### ISSUE TITLE
新版本xray漏洞扫描有bug【已经测试1.2.0】

### ISSUE THREAD

**Issue by LeoHuang2015** [chaitin/xray#834]
开始以为是rad问题，经过测试发现，1.2.0只能扫描少量漏洞，情况如下：
以扫描：http://demo.aisec.cn/demo/aisec/  为例：
老版本（0.14.0）：

ID | Plugin / VulnType | Target | CreateTime
-- | -- | -- | --
#1 | sqldet | http://demo.aisec.cn/demo/aisec/ajax_link.php | 2020-08-17 13:48:52
#2 | xss | http://demo.aisec.cn/demo/aisec/js_link.php | 2020-08-17 13:48:54
#3 | sqldet | http://demo.aisec.cn/demo/aisec/js_link.php | 2020-08-17 13:48:55
#4 | sqldet | http://demo.aisec.cn/demo/aisec/html_link.php | 2020-08-17 13:48:56
#5 | sqldet | http://demo.aisec.cn/demo/aisec/post_link.php | 2020-08-17 13:48:59
#6 | brute_force | http://demo.aisec.cn/demo/aisec/login2.php? | 2020-08-17 13:49:02
#7 | sqldet | http://demo.aisec.cn/demo/aisec/click_link.php | 2020-08-17 13:49:05

新版本（1.2.0）：

ID | Target | PluginName / VulnType | CreateTime
-- | -- | -- | --
  | 1 | http://demo.aisec.cn/demo/aisec/js_link.php | xss | 2020-08-17 13:51:09
  | 2 | http://demo.aisec.cn/demo/aisec/login2.php? | brute_force | 2020-08-17 13:51:12

**Comment by zema1** [comment]
你是咋测的 用代理试下呢

**Comment by LeoHuang2015** [comment]
> 你是咋测的 用代理试下呢

rad + xray.  win10: xray_windows_amd64.exe    rad_windows_amd64.exe

**Comment by cookie9104** [comment]
我这边测试 好想也是这样

**Comment by Ksharp12138** [comment]
这边使用这条命令./xray_windows_amd64 webscan --basic-crawler http://testphp.vulnweb.com/ --html-output xray-crawler-testphp.html，针对1.2.0版本的跑的时候检测到一个弱口令页面就结束爬虫了，1.1.8使用同样的命令可以一直跑

**Comment by zema1** [comment]
> > 你是咋测的 用代理试下呢
> 
> 1. rad + xray.  win10: xray_windows_amd64.exe    rad_windows_amd64.exe
> 2. 浏览器挂代理测试一样的情况；

这个问题今天发版会修复，是因为之前页面相似度调整了一下，感谢反馈~

**Comment by zema1** [comment]
1.3.0 已修复

**Comment by LeoHuang2015** [comment]
> 1.3.0 已修复

好的，等下回头用新版。 兄弟可以整个高级版的lincense麽
