### ISSUE TITLE
xray reverse最多能负载几个client

### ISSUE THREAD

**Issue by aboutbo** [chaitin/xray#879]

**Comment by zema1** [comment]
没有做过这个层面的压测，感觉正常使用可以忽略这个限制，理论可以随便上千。

**Comment by aboutbo** [comment]
> 没有做过这个层面的压测，感觉正常使用可以忽略这个限制，理论可以随便上千。

最近做测试的时候，一个reverse带了大概10个xray client，有个xray client就开始出现报错
版本1.1.8
`
[ERRO] 2020-09-02 11:52:39 [reverse:fetch.go:137] Post "http://45.254.64.7:8081/_/api/fetch": dial tcp 192.168.1.2:8081: i/o timeout

[ERRO] 2020-09-02 11:52:43 [reverse:fetch.go:137] Post "http://45.254.64.7:8081/_/api/fetch": dial tcp 192.168.1.2:8081: i/o timeout

[ERRO] 2020-09-02 11:52:47 [reverse:fetch.go:137] Post "http://45.254.64.7:8081/_/api/fetch": dial tcp 192.168.1.2:8081: i/o timeout

[ERRO] 2020-09-02 11:52:52 [reverse:fetch.go:137] Post "http://45.254.64.7:8081/_/api/fetch": dial tcp 192.168.1.2:8081: i/o timeout

[ERRO] 2020-09-02 11:52:56 [reverse:fetch.go:137] Post "http://45.254.64.7:8081/_/api/fetch": dial tcp 192.168.1.2:8081: i/o timeout`
