### ISSUE TITLE
关于xray干扰验证码输入的建议

### ISSUE THREAD

**Issue by no001ce** [chaitin/xray#889]
1、rad 联合 xray被动扫描，在rad开的浏览器输入验证码会被xray破坏掉，导致验证码很难成功输入；
2、burp 联合 xray 被动扫描也会出现如此情况，但是burp可以暂时关闭代理转发，从而登陆成功后再开启转发到xray；
3、可不可以增加一个暂停功能嘞，例如像dirsearch那样按了ctrl+c后，可以选择结束或者继续。

**Comment by zema1** [comment]
这个问题再考虑下，处理起来要比 dirseach 复杂的多。

**Comment by Jarcis-cy** [comment]
rad的wait login应该能解决
