### ISSUE TITLE
文件泄漏误报

### ISSUE THREAD

**Issue by 1c3z** [chaitin/xray#9]
我来举个例子
/xray_linux_amd64 webscan --plugins dirscan --url https://api.su.baidu.com/  

![image](https://user-images.githubusercontent.com/9052484/59892743-f3a97c00-940c-11e9-8566-b4a711ee1695.png)

![image](https://user-images.githubusercontent.com/9052484/59892766-0e7bf080-940d-11e9-846f-17e14092d6f7.png)

**Comment by dingafter** [comment]
把路径当参数接收的话！响应才会这样吧！这个规则应该是检查响应状态码。一般访问资源对象不存在不都是恢复40xm嘛？

**Comment by virusdefender** [comment]
这是个 api，不存在也返回 json，比较特殊，请 @phith0n 来看下。

**Comment by UUUUnotfound** [comment]
我jio得可以
`curl https://api.su.baidu.com/source_not_exist_{timestamp}_{randint}
{"errors": [{"message": null}], "messages": [{"client_uuid": "7dd0ce3a6c0c07e1"}], "result": {}, "success": false}`

先检测不存在的路径,后面自动识别直接对比默认返回包,超过3-5次为默认返回,减少误报,(强度更高可以删除返回中"source_not_exist_{timestamp}_{randint}",{timestamp},{randint}字样去匹配,或者其他相似度检测)

**Comment by phith0n** [comment]
我看了一下，这个是页面比较算法还不完善导致的。

https://api.su.baidu.com 这个站点返回的内容每次是不一样的：

![image](https://user-images.githubusercontent.com/5711185/59894349-de375080-9412-11e9-8780-5e1e425f8b96.png)

Client UUID的值在发生变化，所以在比较页面的时候没有认为这个是404页面。现在比较页面的算法仅支持HTML，之后应该会加入json的相似度比较。

**Comment by 1c3z** [comment]
您好，这个有修复计划么。。 
扫描到的页面是否可以加入一个二次确定的逻辑。。

**Comment by phith0n** [comment]
下个版本应该就有了，二次确认大部分规则是有的，不过有些规则不太好确认，比如keys和secret这种页面，没有特定的规则。ini文件理论上也有二次确认，不过查找的是`[`这个关键字，由于json里也有`[`，所以也报出来了。

**Comment by phith0n** [comment]
https://github.com/chaitin/xray/releases/tag/0.6.0
