### ISSUE TITLE
【bug】linux服务器scp远程拷贝 Html包括报告文件时，xray自动kill 

### ISSUE THREAD

**Issue by gxhc520** [chaitin/xray#912]
RT

**Comment by virusdefender** [comment]
oom 了吧，和 scp 没关系，见 https://docs.xray.cool/#/guide/faq?id=xray-%e5%9b%a0%e4%b8%ba-out-of-memory-%e8%80%8c%e5%b4%a9%e6%ba%83%e6%88%96%e8%a2%ab%e6%9d%80%e6%ad%bb
