### ISSUE TITLE
rad 搭配 xray 扫目录的问题

### ISSUE THREAD

**Issue by EASY233** [chaitin/xray#914]
在使用Rad搭配xray扫描的时候发现无法扫描出来如备份文件，敏感信息等漏洞出来，这是为什么呢?
例子:
使用普通扫描:xray webscan --url http://xx.com
![image](https://user-images.githubusercontent.com/48321348/97794582-ede5bc80-1c36-11eb-843f-a3e54bf20eec.png)
搭配Rad进行扫描:
高级版:
xray.exe  webscan --browser-crawler http://xx.com
什么漏洞也扫描不出来
是bug吗？如果是的话希望能够尽早修复，如果是的话我的使用有的问题麻烦指正一下问题出现在哪里，非常感谢

**Comment by zema1** [comment]
感觉是非预期行为，可以交流群里私聊我 (Koalr) 地址看下

**Comment by zema1** [comment]
有点忘了这个有没有修复了 如果还有问题再找我看下吧
