### ISSUE TITLE
建议xray出一个检测网站是使用shiro的功能并输出网站

### ISSUE THREAD

**Issue by Oldman19** [chaitin/xray#915]
之前挖某src时，xray扫出了网站存在shiro，但是因为对方有waf，xray没有攻击成功，就没有输出到报告里，这样就会出现误报。当时我对xray发送的包抓包修改绕过waf后拿到了shell。

**Comment by zema1** [comment]
新版本 shiro 的漏洞检测会输出两个漏洞：

+ defaultkey 表示目标是 shiro 站点，并且枚举到了秘钥
+ rememberme  已经发现可以回显的命令执行

所以感觉你可以关注下第一个漏洞
