### ISSUE TITLE
host 被重写问题

### ISSUE THREAD

**Issue by Fuinow** [chaitin/xray#916]
有一个 nginx 只能带特定 host 才能访问，否则断开链接，但发现 host 会被重写，导致无法扫描
![QQ20201104-0](https://user-images.githubusercontent.com/29170314/98091718-be49e500-1ec0-11eb-9451-3ceae412ed95.png)

**Comment by zema1** [comment]
这个 proxy 就是 xray 的起proxy 么

**Comment by Fuinow** [comment]
是的

**Comment by zema1** [comment]
看了一眼，这个是 go http 标准库的行为，到 xray 处理的时候已经没有原始的 host 信息了。https://golang.org/src/net/http/request.go
![image](https://user-images.githubusercontent.com/20637881/99340136-6482eb00-28c2-11eb-9493-f1162637a86b.png)


如果有这种需求，可以绑定个 host。再请求就没问题了。
