### ISSUE TITLE
新版得xray1.4.1与crawlergo联动失败

### ISSUE THREAD

**Issue by ZZtac** [chaitin/xray#922]
新版得xray1.4.1与crawlergo联动失败
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
47.xxx - - [08/Nov/2020 11:39:09] "[37mPOST /webhook HTTP/1.1[0m" 200 -
47.xxx- - [08/Nov/2020 11:39:14] "[37mPOST /webhook HTTP/1.1[0m" 200 -
47.xxx - - [08/Nov/2020 11:39:14] "[37mPOST /webhook HTTP/1.1[0m" 200 -
47.xxx - - [08/Nov/2020 11:39:15] "[37mPOST /webhook HTTP/1.1[0m" 200 -
47.xxx - - [08/Nov/2020 11:39:17] "[37mPOST /webhook HTTP/1.1[0m" 200 -
47.xxx - - [08/Nov/2020 11:39:19] "[37mPOST /webhook HTTP/1.1[0m" 200 -
47.xxx - - [08/Nov/2020 11:39:19] "[37mPOST /webhook HTTP/1.1[0m" 200 -
47.xxx - - [08/Nov/2020 11:39:24] "[37mPOST /webhook HTTP/1.1[0m" 200 -
发送成功，但微信没有接到消息。同样得命令，1.3.3接到设备信息，希望尽快处理
xray:.\xray_windows_amd64.exe webscan --listen 0.0.0.0:7777 --html-output 1.html --webhoo
k-output http://47.xxx:5000/webhook

**Comment by zema1** [comment]
你的 server 已经收到消息了，那说明就不是 xray 的问题。 新版 webhook 消息格式有改动，可能需要对应改一下 https://docs.xray.cool/#/webhook/webhook

**Comment by ZZtac** [comment]
但是同样的命令,1.33接到了消息，是新版 webhook 消息格式原因吗？

**Comment by ZZtac** [comment]
感谢
