### ISSUE TITLE
扫描增加定时重启宽带

### ISSUE THREAD

**Issue by gxhc520** [chaitin/xray#931]
需求来源
每次遇到阿里云这些，扫描不到十分钟，这些云直接封杀IP了,导致大量漏报

需求：
可以自定义配置宽带（电信）账号密码，定时重启宽带（获取新ip），在重启过程中，xray暂时停止扫描，重启成功后再恢复扫描。

**Comment by zema1** [comment]
听起来这不是 xray 该做的事
