### ISSUE TITLE
扫描任务时卡住，按回车恢复

### ISSUE THREAD

**Issue by juershuai** [chaitin/xray#932]
扫描个别网站的时候，命令行窗口卡住不动，半小时任何消息都没有，按了回车立即恢复。 ip没有被封，访问网站正常

**Comment by zema1** [comment]
无图无真相，麻烦提供下对应的版本，截图和可能的复现步骤，这样更方便我们解决问题。

**Comment by juershuai** [comment]
![1605670372(1)](https://user-images.githubusercontent.com/47327383/99479798-d37b4500-2991-11eb-9db7-109fe1649f4c.jpg)
1.3.3高级版，默认配置

**Comment by zema1** [comment]
看起来是你扫的网站有 waf 之类的，请求大量超时了。

**Comment by juershuai** [comment]
按理说应该有个超时时间限制吧，超时时间太长了也没有自动跳过，就卡在这里不动弹...

**Comment by zema1** [comment]
麻烦用刚发的1.4.5 试下吧，如果还有问题可以再反馈

**Comment by maybe-why-not** [comment]
windows cmd快速编辑模式bug
https://zhuanlan.zhihu.com/p/143009848
