### ISSUE TITLE
目录的几个疑问

### ISSUE THREAD

**Issue by xb1ack** [chaitin/xray#935]
当xray收到一个请求如：http://aa.com/x/y/z   xray应该对xy每个目录进行一次扫描

当第二次收到 http://aa.com/x/y/z 就不用对http://aa.com/ http://aa.com/x  http://aa.com/x/y/   再扫描一次了，我看了下结果xray没对这个进行去重，就会造成重复扫描

**Comment by zema1** [comment]
> 当xray收到一个请求如：http://aa.com/x/y/z xray应该对xy每个目录进行一次扫描

这个不会对每个目录扫，只会扫 http://aa.com/x/y/

后面也就不存在重复扫描的问题。预期设计是这样，如果有观察到不一样的情况，可以再说一下。

指的一说的是，rad 有自动的路径拆解，如果搭配使用可能会产生你说的情况，但这不是 xray 漏洞扫描自己的行为。
