### ISSUE TITLE
漏洞识别分类错误

### ISSUE THREAD

**Issue by xsser** [chaitin/xray#936]
**版本**
Version: 1.4.2/d579ba25/COMMUNITY

[xray 1.4.2/d579ba25]
Build: [2020-11-10] [linux/amd64] [RELEASE/COMMUNITY]
Compiler Version: go version go1.14.4 linux/amd64

**URL** 
http://10.211.55.2/vulnerabilities/brute/?Login=Login&password=1&username=admin%27and%2F%2A%2A%2Fextractvalue%281%2Cconcat%28char%28126%29%2Cmd5%281131450987%29%29%29and%27

**请求**
GET /vulnerabilities/brute/?Login=Login&password=1&username=admin%27and%2F%2A%2A%2Fextractvalue%281%2Cconcat%28char%28126%29%2Cmd5%281131450987%29%29%29and%27 HTTP/1.1 Host: 10.211.55.2 User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2 Cookie: PHPSESSID=8qerulgesacbnm1j67l4djtpv1; security=low Referer: http://10.211.55.2/vulnerabilities/brute/ Upgrade-Insecure-Requests: 1 Accept-Encoding: gzip  Copy

**响应**
HTTP/1.1 200 OK Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0 Content-Length: 65 Content-Type: text/html Date: Wed, 18 Nov 2020 06:34:39 GMT Expires: Thu, 19 Nov 1981 08:52:00 GMT Pragma: no-cache Server: Apache/2.4.7 (Ubuntu) X-Powered-By: PHP/5.5.9-1ubuntu4.20  <pre>XPATH syntax error: '~fc19fdcbd5561fe05466e6a2ea5b353'</pre>

<img width="1738" alt="图片" src="https://user-images.githubusercontent.com/1850771/99498915-1994d080-29b3-11eb-9d68-6c80f8e68496.png">

**Comment by virusdefender** [comment]
那里面有sql注入漏洞么

**Comment by xsser** [comment]
> 那报告里面有sql注入漏洞么

有的

**Comment by zema1** [comment]
那就不算分类错误，这个漏洞作为sql注入和系统信息错误没问题
