### ISSUE TITLE
burp 配合xray时， Repeater的错误的问题 

### ISSUE THREAD

**Issue by kakakpy** [chaitin/xray#938]
当burp对 请求包 ，修改host头后进行repeter ， 则会无视Target的设置，直接访问修改后的host的地址。
![image](https://user-images.githubusercontent.com/39979275/99627446-532b1180-2a6f-11eb-8162-895a8b486d38.png)

**Comment by kakakpy** [comment]
这一条会影响burp的扫描结果以及测试结果。

**Comment by zema1** [comment]
related to https://github.com/chaitin/xray/issues/916#issuecomment-728651373

请点击链接查看，这是标准库行为，暂不打算处理
