### ISSUE TITLE
dirscan插件问题

### ISSUE THREAD

**Issue by a1most** [chaitin/xray#939]
使用dirscan插件时，指定一个字典绝对路径，如下：
![image](https://user-images.githubusercontent.com/34560797/99630494-fa5e7780-2a74-11eb-9480-477eb5fa3339.png)
启动xray之后使用burp查看记录
![image](https://user-images.githubusercontent.com/34560797/99630613-2e399d00-2a75-11eb-978d-2a6927693464.png)
发现只记录了5百多条，远不够字典条数。
求大佬解答！

**Comment by zema1** [comment]
1.6.0 版本已修复
