### ISSUE TITLE
mac版sqldet插件出现请求报错

### ISSUE THREAD

**Issue by nszy007** [chaitin/xray#956]
macos版本为11.1
测试环境因故不能公开，为post提交的延时注入。
报错信息如下：
[ERRO] 2020-12-22 22:50:43 [sqldet:detector.go:54] Post "http://www.xxxxx.xx/admin.php/Login/index.html": dial tcp: i/o timeout
[ERRO] 2020-12-22 22:50:43 [sqldet:detector.go:426] Sample number 0/3 is not enough
[ERRO] 2020-12-22 22:50:43 [controller:runner.go:76] need scheduler to requeue the task
[ERRO] 2020-12-22 22:50:43 [sqldet:detector.go:54] Post "http://www.xxxxx.xx/admin.php/Login/index.html": dial tcp: i/o timeout
[ERRO] 2020-12-22 22:50:43 [sqldet:detector.go:426] Sample number 0/3 is not enough
[ERRO] 2020-12-22 22:50:43 [controller:runner.go:76] need scheduler to requeue the task

windows版测试正常。

**Comment by virusdefender** [comment]
网络问题导致部分检测过程失败，可以重试解决，应该和系统无关。

**Comment by nszy007** [comment]
肯定不是网络问题啊…
网络问题会sqlmap就正常吗？会用windows版就正常吗？
